
'use client';

import { JobRecommendationResponse } from "@/ai/schemas/recommend-jobs-schema";
import { consultants } from "./consultant-data";

export type User = {
  id: string;
  name: string;
  avatarUrl: string;
  dataAiHint?: string;
  isBot?: boolean;
  mainExpertise?: string;
  experience?: string;
  successfulCandidates?: number;
  strengths?: string[];
  avatar?: string; // Add avatar for compatibility
};

export type Attachment = {
  type: 'image' | 'video' | 'file';
  url: string;
  fileName?: string;
}

export type Message = {
  id: string;
  sender: User;
  text: string;
  timestamp: string;
  isLoading?: boolean;
  recommendations?: JobRecommendationResponse['recommendations'];
  suggestedReplies?: string[];
  attachment?: Attachment;
};

export type Conversation = {
  id: string;
  participants: User[];
  messages: Message[];
};

// Define different user personas for testing
export const loggedInUser: User = {
  id: 'user-0',
  name: 'Lê Ngọc Hân',
  avatarUrl: 'https://placehold.co/100x100.png?text=Me',
};

export const guestUser: User = {
  id: 'user-guest-123', // A different ID for the guest
  name: 'Khách',
  avatarUrl: 'https://placehold.co/100x100.png?text=G',
};

// This will be the actively used user object, mutated by AuthContext
export let currentUser: User = guestUser;

// AI Bot persona
export const helloJobBot: User = {
    id: 'bot-hellojob',
    name: 'HelloJob AI',
    avatarUrl: '/img/favi2.png',
    dataAiHint: 'friendly robot mascot',
    isBot: true,
};


// Initial conversations data
export const conversations: Conversation[] = [
  {
    id: 'convo-bot-hellojob',
    participants: [currentUser, helloJobBot],
    messages: [
      // This will be dynamically generated by ChatContext
    ],
  },
];

// Re-export consultants to be used by client components
export { consultants };
