
export type HollandQuestion = {
  id: number;
  text: string;
};

export type HollandGroup = {
  code: 'R' | 'I' | 'A' | 'S' | 'E' | 'C';
  name: string;
  description: string;
  questions: HollandQuestion[];
};

// =================================================================
// BỘ CÂU HỎI CHO HỌC SINH THCS (12-15 TUỔI)
// =================================================================
export const hollandDataThcs: HollandGroup[] = [
  {
    code: 'R',
    name: 'Realistic - Nhóm Kỹ thuật',
    description: 'Em có thích làm việc với tay chân, máy móc, và các hoạt động thể chất không?',
    questions: [
        { id: 1, text: 'Tháo lắp, sửa chữa đồ chơi hoặc các vật dụng đơn giản trong nhà.' },
        { id: 2, text: 'Lắp ráp mô hình (robot, máy bay, tàu thủy).' },
        { id: 3, text: 'Chơi các môn thể thao vận động (đá bóng, bơi lội, chạy bộ).' },
        { id: 4, text: 'Làm các thí nghiệm vật lý, hóa học đơn giản.' },
        { id: 5, text: 'Trồng cây, chăm sóc vườn.' },
        { id: 6, text: 'Sử dụng các dụng cụ như búa, kìm, tua-vít.' },
        { id: 7, text: 'Chơi các trò chơi điện tử về xây dựng, chiến thuật.' },
        { id: 8, text: 'Tìm hiểu cách hoạt động của xe đạp, xe máy.' },
        { id: 9, text: 'Đi cắm trại, dã ngoại, khám phá thiên nhiên.' },
        { id: 10, text: 'Làm các công việc thủ công, tạo ra sản phẩm cụ thể.' },
        { id: 11, text: 'Học môn Công nghệ, Kỹ thuật ở trường.' },
        { id: 12, text: 'Thích các nghề như thợ sửa chữa, kỹ sư, nông dân.' },
        { id: 13, text: 'Chơi các môn thể thao đối kháng.' },
        { id: 14, text: 'Tự tay làm một món đồ trang trí cho phòng của mình.' },
    ],
  },
  {
    code: 'I',
    name: 'Investigative - Nhóm Nghiên cứu',
    description: 'Em có thích quan sát, tìm tòi, khám phá và giải quyết các câu hỏi khó không?',
    questions: [
        { id: 1, text: 'Đọc sách, xem phim tài liệu về khoa học, lịch sử, vũ trụ.' },
        { id: 2, text: 'Giải các bài toán khó, các câu đố logic.' },
        { id: 3, text: 'Tìm hiểu về máy tính, cách viết các dòng lệnh đơn giản.' },
        { id: 4, text: 'Quan sát các loài động vật, thực vật và tìm hiểu về chúng.' },
        { id: 5, text: 'Thích các môn học như Toán, Lý, Hóa, Sinh.' },
        { id: 6, text: 'Thích tự tìm câu trả lời cho những câu hỏi "Tại sao?".' },
        { id: 7, text: 'Chơi các trò chơi đòi hỏi suy luận, điều tra (cờ vua, board game).' },
        { id: 8, text: 'Tìm hiểu về cơ thể người, các loại bệnh tật.' },
        { id: 9, text: 'Sưu tầm và phân loại một thứ gì đó (tem, côn trùng, lá cây).' },
        { id: 10, text: 'Thích làm việc một mình và tập trung suy nghĩ.' },
        { id: 11, text: 'Tò mò về cách các phát minh ra đời.' },
        { id: 12, text: 'Thích các nghề như nhà khoa học, bác sĩ, lập trình viên.' },
        { id: 13, text: 'Phân tích một vấn đề ra thành nhiều phần nhỏ để hiểu rõ hơn.' },
        { id: 14, text: 'So sánh ưu nhược điểm của các sự vật, hiện tượng.' },
    ],
  },
  {
    code: 'A',
    name: 'Artistic - Nhóm Nghệ thuật',
    description: 'Em có thích sự sáng tạo, tưởng tượng và thể hiện bản thân qua các hình thức nghệ thuật không?',
    questions: [
        { id: 1, text: 'Vẽ tranh, tô màu, trang trí.' },
        { id: 2, text: 'Hát, chơi một loại nhạc cụ.' },
        { id: 3, text: 'Viết truyện, làm thơ.' },
        { id: 4, text: 'Chụp ảnh, quay video và chỉnh sửa.' },
        { id: 5, text: 'Tự nghĩ ra các điệu nhảy, múa.' },
        { id: 6, text: 'Tham gia các vở kịch, diễn xuất ở trường.' },
        { id: 7, text: 'Thiết kế quần áo, trang phục cho búp bê hoặc nhân vật game.' },
        { id: 8, text: 'Thích môn Âm nhạc, Mỹ thuật.' },
        { id: 9, text: 'Trang trí phòng ốc, góc học tập của mình.' },
        { id: 10, text: 'Làm các đồ thủ công (handmade) để tặng bạn bè.' },
        { id: 11, text: 'Thích những ý tưởng mới lạ, độc đáo, không giống ai.' },
        { id: 12, text: 'Thích các nghề như họa sĩ, ca sĩ, nhà văn, diễn viên.' },
        { id: 13, text: 'Tưởng tượng ra những câu chuyện, thế giới không có thật.' },
        { id: 14, text: 'Bày tỏ cảm xúc của mình một cách tự do (qua tranh vẽ, bài hát...).' },
    ],
  },
  {
    code: 'S',
    name: 'Social - Nhóm Xã hội',
    description: 'Em có thích làm việc, trò chuyện và giúp đỡ người khác không?',
    questions: [
        { id: 1, text: 'Kèm bạn học, giải thích bài cho bạn bè.' },
        { id: 2, text: 'Tham gia các hoạt động tình nguyện, công tác xã hội của trường, lớp.' },
        { id: 3, text: 'Lắng nghe tâm sự và cho bạn bè lời khuyên.' },
        { id: 4, text: 'Chăm sóc em nhỏ hoặc người thân bị ốm.' },
        { id: 5, text: 'Thích làm việc nhóm hơn làm việc một mình.' },
        { id: 6, text: 'Làm quen, nói chuyện với các bạn mới.' },
        { id: 7, text: 'Tổ chức các hoạt động, trò chơi cho lớp, nhóm.' },
        { id: 8, text: 'Làm lớp trưởng, lớp phó hoặc các cán bộ lớp.' },
        { id: 9, text: 'Hòa giải khi bạn bè có mâu thuẫn, cãi nhau.' },
        { id: 10, text: 'Chia sẻ đồ dùng, đồ ăn của mình cho người khác.' },
        { id: 11, text: 'Thích các môn học như Giáo dục công dân, Ngữ văn.' },
        { id: 12, text: 'Thích các nghề như giáo viên, tư vấn tâm lý, nhân viên công tác xã hội.' },
        { id: 13, text: 'Phát biểu ý kiến trong các buổi sinh hoạt lớp.' },
        { id: 14, text: 'Quan tâm đến các vấn đề trong xã hội.' },
    ],
  },
  {
    code: 'E',
    name: 'Enterprising - Nhóm Quản lý',
    description: 'Em có thích lãnh đạo, thuyết phục người khác và đặt ra các mục tiêu để thực hiện không?',
    questions: [
        { id: 1, text: 'Làm trưởng nhóm trong các bài tập, dự án của lớp.' },
        { id: 2, text: 'Thuyết phục bố mẹ, bạn bè đồng ý với ý kiến của mình.' },
        { id: 3, text: 'Nảy ra ý tưởng kinh doanh nhỏ (bán đồ ăn vặt, đồ handmade).' },
        { id: 4, text: 'Phát biểu, trình bày ý kiến trước lớp.' },
        { id: 5, text: 'Thích tham gia các cuộc thi, tranh luận.' },
        { id: 6, text: 'Tổ chức một buổi đi chơi, một sự kiện cho nhóm bạn.' },
        { id: 7, text: 'Đặt mục tiêu cho bản thân (ví dụ: đạt điểm cao, học một kỹ năng mới) và cố gắng hoàn thành.' },
        { id: 8, text: 'Thích làm những việc có tầm ảnh hưởng đến người khác.' },
        { id: 9, text: 'Thích các trò chơi có tính cạnh tranh, thi đấu.' },
        { id: 10, text: 'Thích được khen ngợi và công nhận.' },
        { id: 11, text: 'Dám thử những điều mới và chấp nhận rủi ro.' },
        { id: 12, text: 'Thích các nghề như giám đốc, quản lý, luật sư, nhà kinh doanh.' },
        { id: 13, text: 'Thương lượng để có được thứ mình muốn.' },
        { id: 14, text: 'Dẫn dắt một đội, nhóm để giành chiến thắng.' },
    ],
  },
  {
    code: 'C',
    name: 'Conventional - Nhóm Nghiệp vụ',
    description: 'Em có thích làm việc với các con số, giấy tờ, và làm theo các quy tắc, hướng dẫn có sẵn không?',
    questions: [
        { id: 1, text: 'Sắp xếp sách vở, góc học tập của mình gọn gàng, ngăn nắp.' },
        { id: 2, text: 'Lập thời gian biểu và thực hiện theo đúng kế hoạch.' },
        { id: 3, text: 'Ghi chép bài cẩn thận, sạch sẽ, rõ ràng.' },
        { id: 4, text: 'Làm thủ quỹ cho lớp, quản lý tiền bạc.' },
        { id: 5, text: 'Thích các công việc đòi hỏi sự chính xác, tỉ mỉ.' },
        { id: 6, text: 'Làm việc với bảng biểu, số liệu.' },
        { id: 7, text: 'Tuân thủ nội quy của trường lớp.' },
        { id: 8, text: 'Kiểm tra lại bài vở kỹ càng để không có sai sót.' },
        { id: 9, text: 'Nhập dữ liệu vào máy tính (gõ văn bản, làm slide).' },
        { id: 10, text: 'Thích các môn học có câu trả lời rõ ràng, đúng hoặc sai.' },
        { id: 11, text: 'Thích làm theo các hướng dẫn có sẵn hơn là tự sáng tạo.' },
        { id: 12, text: 'Thích các nghề như kế toán, thư ký, thủ thư, nhân viên ngân hàng.' },
        { id: 13, text: 'Lưu giữ cẩn thận các giấy tờ, tài liệu quan trọng.' },
        { id: 14, text: 'Làm các công việc lặp đi lặp lại một cách chính xác.' },
    ],
  },
];


// =================================================================
// BỘ CÂU HỎI CHO HỌC SINH PTTH & SINH VIÊN (16-22 TUỔI)
// =================================================================
export const hollandDataPtthSv: HollandGroup[] = [
  {
    code: 'R',
    name: 'Realistic - Nhóm Kỹ thuật',
    description: 'Bạn có thiên hướng làm việc với các hệ thống, công cụ, máy móc và các hoạt động đòi hỏi sự khéo léo chân tay không?',
    questions: [
        { id: 1, text: 'Sửa chữa, nâng cấp các thiết bị điện tử (máy tính, điện thoại).' },
        { id: 2, text: 'Tham gia các câu lạc bộ chế tạo robot, xe mô hình.' },
        { id: 3, text: 'Làm việc trong các xưởng thực hành (cơ khí, mộc).' },
        { id: 4, text: 'Theo học các ngành kỹ thuật (Cơ khí, Điện, Xây dựng, Tự động hóa).' },
        { id: 5, text: 'Chơi các môn thể thao đòi hỏi kỹ thuật và sức bền.' },
        { id: 6, text: 'Đọc và hiểu các bản vẽ kỹ thuật, sơ đồ mạch điện.' },
        { id: 7, text: 'Tìm hiểu về nông nghiệp công nghệ cao, các hệ thống tưới tiêu tự động.' },
        { id: 8, text: 'Làm các công việc bán thời gian liên quan đến thể chất (bốc xếp, phục vụ).' },
        { id: 9, text: 'Tự tay cải tạo, trang trí lại không gian sống của mình.' },
        { id: 10, text: 'Thích tìm hiểu về cơ chế hoạt động của các loại động cơ, vũ khí.' },
        { id: 11, text: 'Lái xe (xe máy, ô tô).' },
        { id: 12, text: 'Ưu tiên các giải pháp thực tế, hiệu quả hơn là các ý tưởng lý thuyết.' },
        { id: 13, text: 'Thích các công việc ngoài trời hơn là ngồi trong văn phòng.' },
        { id: 14, text: 'Quan tâm đến các ngành nghề như kiến trúc sư, kỹ sư, phi công, nông dân hiện đại.' },
    ],
  },
  {
    code: 'I',
    name: 'Investigative - Nhóm Nghiên cứu',
    description: 'Bạn có thích tìm tòi, phân tích, giải quyết các vấn đề phức tạp và làm việc với các ý tưởng, lý thuyết không?',
    questions: [
        { id: 1, text: 'Thực hiện các đề tài, dự án nghiên cứu khoa học ở trường.' },
        { id: 2, text: 'Đọc các sách, bài báo chuyên ngành (khoa học, kinh tế, xã hội).' },
        { id: 3, text: 'Lập trình, viết code, phát triển thuật toán.' },
        { id: 4, text: 'Phân tích số liệu, làm thống kê để tìm ra các quy luật.' },
        { id: 5, text: 'Theo học các ngành khoa học cơ bản (Toán, Lý, Hóa, Sinh).' },
        { id: 6, text: 'Tham gia các cuộc thi học thuật, Olympic.' },
        { id: 7, text: 'Tìm hiểu sâu về một lĩnh vực mình quan tâm (kinh tế vĩ mô, vật lý lượng tử).' },
        { id: 8, text: 'Thích tự học, tự tìm tòi kiến thức mới trên Internet.' },
        { id: 9, text: 'Viết luận, phân tích các tác phẩm văn học, sự kiện lịch sử.' },
        { id: 10, text: 'Làm việc trong phòng thí nghiệm.' },
        { id: 11, text: 'Thích tranh luận dựa trên logic và bằng chứng.' },
        { id: 12, text: 'Quan tâm đến các ngành nghề như nhà khoa học, lập trình viên, nhà phân tích dữ liệu, bác sĩ.' },
        { id: 13, text: 'Hoài nghi và kiểm chứng lại thông tin trước khi tin.' },
        { id: 14, text: 'Xây dựng các mô hình lý thuyết để giải thích các hiện tượng.' },
    ],
  },
  {
    code: 'A',
    name: 'Artistic - Nhóm Nghệ thuật',
    description: 'Bạn có thích thể hiện bản thân một cách sáng tạo, độc đáo và làm việc trong môi trường linh hoạt, không theo khuôn mẫu không?',
    questions: [
        { id: 1, text: 'Sáng tác (văn, thơ, nhạc, kịch bản).' },
        { id: 2, text: 'Chơi thành thạo một nhạc cụ hoặc ca hát.' },
        { id: 3, text: 'Thiết kế đồ họa, website, giao diện ứng dụng.' },
        { id: 4, text: 'Nhiếp ảnh, quay phim, dựng phim.' },
        { id: 5, text: 'Tham gia các câu lạc bộ kịch, nhảy, âm nhạc.' },
        { id: 6, text: 'Vẽ (tranh sơn dầu, màu nước, digital painting).' },
        { id: 7, text: 'Thiết kế thời trang, phối đồ (mix & match).' },
        { id: 8, text: 'Viết blog, làm YouTuber, sáng tạo nội dung trên mạng xã hội.' },
        { id: 9, text: 'Theo học các ngành về thiết kế, mỹ thuật, sân khấu điện ảnh, báo chí.' },
        { id: 10, text: 'Thích sự khác biệt, phá cách và thể hiện cá tính riêng.' },
        { id: 11, text: 'Cảm thụ và phân tích các tác phẩm nghệ thuật.' },
        { id: 12, text: 'Quan tâm đến các nghề như nhà thiết kế, nhạc sĩ, đạo diễn, nhà báo, content creator.' },
        { id: 13, text: 'Làm việc dựa trên cảm hứng và trực giác.' },
        { id: 14, text: 'Tạo ra những thứ mới mẻ, chưa từng có trước đây.' },
    ],
  },
  {
    code: 'S',
    name: 'Social - Nhóm Xã hội',
    description: 'Bạn có thích giao tiếp, kết nối, giảng dạy, và giúp đỡ người khác giải quyết các vấn đề của họ không?',
    questions: [
        { id: 1, text: 'Tham gia các hoạt động tình nguyện, các tổ chức phi chính phủ (NGO).' },
        { id: 2, text: 'Làm gia sư, hướng dẫn học tập cho người khác.' },
        { id: 3, text: 'Tư vấn, tham vấn cho bạn bè về các vấn đề trong học tập, cuộc sống.' },
        { id: 4, text: 'Làm các công việc bán thời gian trong ngành dịch vụ (nhà hàng, khách sạn).' },
        { id: 5, text: 'Theo học các ngành Sư phạm, Tâm lý học, Công tác xã hội, Y tế.' },
        { id: 6, 'text': 'Tổ chức các sự kiện, hoạt động tập thể cho trường, lớp, câu lạc bộ.' },
        { id: 7, text: 'Thích làm việc trong môi trường có nhiều người, nhiều sự tương tác.' },
        { id: 8, text: 'Dễ dàng kết bạn và xây dựng các mối quan hệ.' },
        { id: 9, text: 'Thuyết trình, nói chuyện trước đám đông.' },
        { id: 10, text: 'Lắng nghe và thấu hiểu cảm xúc của người khác.' },
        { id: 11, text: 'Làm việc trong các đội, nhóm, dự án chung.' },
        { id: 12, text: 'Quan tâm đến các nghề như giáo viên, bác sĩ, chuyên viên tư vấn, nhân viên nhân sự.' },
        { id: 13, text: 'Chăm sóc, hỗ trợ những người yếu thế trong xã hội.' },
        { id: 14, text: 'Giải quyết các xung đột, mâu thuẫn một cách hòa bình.' },
    ],
  },
  {
    code: 'E',
    name: 'Enterprising - Nhóm Quản lý',
    description: 'Bạn có thích lãnh đạo, quản lý, thuyết phục và tạo ra ảnh hưởng để đạt được các mục tiêu về kinh doanh hoặc tổ chức không?',
    questions: [
        { id: 1, text: 'Làm chủ nhiệm câu lạc bộ, trưởng một dự án.' },
        { id: 2, text: 'Bắt đầu một dự án kinh doanh nhỏ hoặc bán hàng online.' },
        { id: 3, text: 'Tham gia các cuộc thi về kinh doanh, marketing, hùng biện.' },
        { id: 4, text: 'Tranh cử vào các vị trí trong hội sinh viên, đoàn trường.' },
        { id: 5, text: 'Thuyết phục người khác đầu tư hoặc tham gia vào dự án của mình.' },
        { id: 6, text: 'Theo học các ngành Quản trị kinh doanh, Marketing, Tài chính, Luật.' },
        { id: 7, text: 'Đọc sách về kinh doanh, khởi nghiệp, kỹ năng lãnh đạo.' },
        { id: 8, text: 'Quản lý tài chính cá nhân, lập kế hoạch chi tiêu, đầu tư.' },
        { id: 9, text: 'Thích đặt ra các mục tiêu đầy tham vọng và chinh phục chúng.' },
        { id: 10, text: 'Đàm phán, thương lượng để đạt được lợi ích tốt nhất.' },
        { id: 11, text: 'Xây dựng mạng lưới quan hệ (networking).' },
        { id: 12, text: 'Quan tâm đến các nghề như doanh nhân, giám đốc, chuyên viên marketing, luật sư, chính trị gia.' },
        { id: 13, text: 'Chịu trách nhiệm về thành công hay thất bại của một nhóm.' },
        { id: 14, text: 'Nói trước đám đông và truyền cảm hứng cho mọi người.' },
    ],
  },
  {
    code: 'C',
    name: 'Conventional - Nhóm Nghiệp vụ',
    description: 'Bạn có thích làm việc với dữ liệu, các con số, tuân thủ các quy trình và tạo ra sự ngăn nắp, có tổ chức không?',
    questions: [
        { id: 1, text: 'Làm việc với phần mềm văn phòng (Word, Excel, PowerPoint).' },
        { id: 2, text: 'Lập kế hoạch chi tiết cho một chuyến đi hoặc một dự án.' },
        { id: 3, text: 'Quản lý chi tiêu cá nhân bằng các ứng dụng hoặc sổ sách.' },
        { id: 4, text: 'Soạn thảo, sắp xếp, lưu trữ tài liệu một cách khoa học.' },
        { id: 5, text: 'Theo học các ngành Kế toán, Kiểm toán, Thư viện, Hành chính văn phòng.' },
        { id: 6, text: 'Kiểm tra lại công việc của mình và người khác để tìm lỗi sai.' },
        { id: 7, text: 'Làm các công việc đòi hỏi sự cẩn thận, chính xác và chú ý đến chi tiết.' },
        { id: 8, text: 'Thích làm việc trong môi trường ổn định, có quy trình rõ ràng.' },
        { id: 9, text: 'Tuân thủ các quy định, thời hạn (deadline).' },
        { id: 10, text: 'Phân tích và xử lý các bộ dữ liệu lớn.' },
        { id: 11, text: 'Thực hiện các công việc có tính lặp lại một cách hiệu quả.' },
        { id: 12, text: 'Quan tâm đến các nghề như kế toán viên, nhân viên ngân hàng, chuyên viên phân tích dữ liệu, thư ký.' },
        { id: 13, text: 'Nhập liệu, quản lý cơ sở dữ liệu.' },
        { id: 14, text: 'Tạo ra các báo cáo, biểu đồ từ các số liệu cho trước.' },
    ],
  },
];


// =================================================================
// BỘ CÂU HỎI CHO NGƯỜI ĐI LÀM (23+ TUỔI)
// =================================================================
export const hollandDataDiLam: HollandGroup[] = [
  {
    code: 'R',
    name: 'Realistic - Nhóm Kỹ thuật',
    description: 'Những người thuộc nhóm này có sở thích và khả năng về kỹ thuật, máy móc, công nghệ. Họ thích làm việc với các vật thể cụ thể, cầm nắm được.',
    questions: [
        { id: 1, text: 'Sửa chữa các thiết bị điện, điện tử trong gia đình hoặc công ty.' },
        { id: 2, text: 'Làm các công việc về cơ khí như tiện, phay, hàn.' },
        { id: 3, text: 'Lái các loại xe lớn hoặc máy móc công trình.' },
        { id: 4, text: 'Làm việc ngoài trời (ví dụ: công trình xây dựng, trang trại).' },
        { id: 5, text: 'Chăm sóc, huấn luyện động vật hoặc làm nông nghiệp.' },
        { id: 6, text: 'Lắp ráp, chế tạo các sản phẩm cơ khí, đồ gỗ.' },
        { id: 7, text: 'Sử dụng thành thạo các công cụ, dụng cụ cầm tay.' },
        { id: 8, text: 'Đọc bản vẽ kỹ thuật, bản vẽ xây dựng.' },
        { id: 9, text: 'Làm công việc về mộc, thiết kế và thi công nội thất.' },
        { id: 10, text: 'Làm vườn, thiết kế cảnh quan.' },
        { id: 11, text: 'Sửa chữa, bảo dưỡng xe máy, ô tô.' },
        { id: 12, text: 'Tham gia các hoạt động thể chất, thể thao đòi hỏi sức mạnh.' },
        { id: 13, text: 'Làm trong lĩnh vực an ninh, quốc phòng, phòng cháy chữa cháy.' },
        { id: 14, text: 'Thám hiểm, khảo sát địa chất hoặc các hoạt động ngoài thiên nhiên.' },
    ],
  },
  {
    code: 'I',
    name: 'Investigative - Nhóm Nghiên cứu',
    description: 'Những người thuộc nhóm này có thiên hướng về quan sát, tìm tòi, khám phá. Họ thích làm việc với các ý tưởng, dữ liệu và giải quyết các vấn đề phức tạp.',
    questions: [
        { id: 1, text: 'Thực hiện các thí nghiệm, nghiên cứu trong phòng lab.' },
        { id: 2, text: 'Đọc sách, tài liệu chuyên sâu về một lĩnh vực nào đó.' },
        { id: 3, text: 'Làm việc trong môi trường y tế, chẩn đoán bệnh.' },
        { id: 4, text: 'Phân tích dữ liệu, thống kê để đưa ra các dự báo, quyết định.' },
        { id: 5, text: 'Giải quyết các vấn đề kỹ thuật phức tạp, tìm ra lỗi hệ thống.' },
        { id: 6, text: 'Nghiên cứu về thị trường, đối thủ cạnh tranh.' },
        { id: 7, text: 'Lập trình máy tính, phát triển phần mềm, trí tuệ nhân tạo.' },
        { id: 8, text: 'Nghiên cứu và phát triển (R&D) sản phẩm mới.' },
        { id: 9, text: 'Viết báo cáo phân tích, các bài báo khoa học.' },
        { id: 10, text: 'Tìm hiểu, khám phá các nguyên lý khoa học, kinh tế, xã hội.' },
        { id: 11, text: 'Sử dụng các công cụ phân tích, chẩn đoán chuyên dụng.' },
        { id: 12, text: 'Làm việc độc lập, đòi hỏi sự tập trung và tư duy logic cao độ.' },
        { id: 13, text: 'Nghiên cứu các vấn đề trừu tượng, mang tính học thuật.' },
        { id: 14, text: 'Điều tra, phân tích nguyên nhân của một sự việc, sự cố.' },
    ],
  },
  {
    code: 'A',
    name: 'Artistic - Nhóm Nghệ thuật',
    description: 'Những người thuộc nhóm này có khả năng sáng tạo, trực giác và trí tưởng tượng phong phú. Họ thích làm việc trong các môi trường không có nhiều quy tắc và thể hiện bản thân qua các sản phẩm nghệ thuật.',
    questions: [
        { id: 1, text: 'Vẽ, thiết kế đồ họa, thiết kế sản phẩm.' },
        { id: 2, text: 'Chơi một loại nhạc cụ, biểu diễn hoặc sáng tác âm nhạc.' },
        { id: 3, text: 'Viết lách (viết sách, báo, kịch bản, nội dung quảng cáo).' },
        { id: 4, text: 'Viết blog, làm podcast, sáng tạo nội dung cho mạng xã hội.' },
        { id: 5, text: 'Chụp ảnh, quay phim chuyên nghiệp.' },
        { id: 6, text: 'Thiết kế thời trang, thiết kế nội thất.' },
        { id: 7, text: 'Làm trong ngành sân khấu, điện ảnh (diễn viên, đạo diễn).' },
        { id: 8, text: 'Làm marketing, quảng cáo, xây dựng thương hiệu.' },
        { id: 9, text: 'Trình diễn nghệ thuật (ca hát, nhảy múa).' },
        { id: 10, text: 'Làm việc với tư cách là một nghệ sĩ tự do.' },
        { id: 11, text: 'Làm các đồ thủ công mỹ nghệ có giá trị cao.' },
        { id: 12, text: 'Nghĩ ra những ý tưởng, chiến dịch mới, độc đáo cho công ty.' },
        { id: 13, text: 'Thể hiện ý tưởng, cảm xúc của bản thân một cách sáng tạo.' },
        { id: 14, text: 'Làm việc trong một môi trường linh hoạt, tự do, không gò bó.' },
    ],
  },
  {
    code: 'S',
    name: 'Social - Nhóm Xã hội',
    description: 'Những người thuộc nhóm này thích làm việc với con người, giúp đỡ, hướng dẫn và chăm sóc người khác. Họ có khả năng về giao tiếp và thấu cảm.',
    questions: [
        { id: 1, text: 'Dạy học, đào tạo hoặc huấn luyện người khác.' },
        { id: 2, text: 'Chăm sóc người bệnh, người già, trẻ em (y tá, điều dưỡng).' },
        { id: 3, text: 'Tư vấn (hướng nghiệp, tâm lý, pháp luật).' },
        { id: 4, text: 'Làm công việc trong các tổ chức xã hội, phi lợi nhuận.' },
        { id: 5, text: 'Làm việc nhóm, hợp tác với nhiều phòng ban, đối tác.' },
        { id: 6, text: 'Tổ chức các sự kiện, hội thảo, hoạt động kết nối.' },
        { id: 7, text: 'Làm trong ngành dịch vụ khách hàng, quản lý quan hệ khách hàng.' },
        { id: 8, 'text': 'Gặp gỡ, nói chuyện, xây dựng mối quan hệ với khách hàng, đối tác.' },
        { id: 9, text: 'Làm công tác nhân sự (tuyển dụng, đào tạo, phát triển nhân viên).' },
        { id: 10, text: 'Giúp đỡ đồng nghiệp giải quyết các vấn đề khó khăn trong công việc.' },
        { id: 11, text: 'Thuyết trình, giới thiệu sản phẩm, dự án trước đám đông.' },
        { id: 12, text: 'Xây dựng và duy trì các mối quan hệ xã hội tốt đẹp.' },
        { id: 13, text: 'Làm trong lĩnh vực y tế, giáo dục, phúc lợi xã hội.' },
        { id: 14, text: 'Giải quyết các mâu thuẫn, xung đột trong tổ chức.' },
    ],
  },
  {
    code: 'E',
    name: 'Enterprising - Nhóm Kinh doanh',
    description: 'Những người thuộc nhóm này có khả năng lãnh đạo, thuyết phục và gây ảnh hưởng đến người khác. Họ thích kinh doanh, quản lý và đặt ra các mục tiêu để đạt được thành công.',
    questions: [
        { id: 1, text: 'Bán một sản phẩm, dịch vụ hoặc một ý tưởng.' },
        { id: 2, text: 'Quản lý một đội nhóm, một phòng ban hoặc một dự án.' },
        { id: 3, text: 'Thuyết phục, tranh luận để bảo vệ quan điểm của mình.' },
        { id: 4, text: 'Phát biểu, diễn thuyết trước các nhà đầu tư, khách hàng.' },
        { id: 5, text: 'Khởi nghiệp, điều hành một công ty riêng.' },
        { id: 6, text: 'Đàm phán, thương lượng các hợp đồng, thương vụ kinh doanh.' },
        { id: 7, text: 'Đặt ra các mục tiêu kinh doanh (KPIs) và dẫn dắt đội nhóm hoàn thành.' },
        { id: 8, text: 'Tìm kiếm cơ hội đầu tư, gia tăng tài sản.' },
        { id: 9, text: 'Tổ chức, điều hành một chiến dịch marketing, bán hàng.' },
        { id: 10, text: 'Chấp nhận rủi ro có tính toán để đạt được lợi nhuận cao.' },
        { id: 11, text: 'Làm việc trong môi trường cạnh tranh, áp lực cao.' },
        { id: 12, text: 'Gây ảnh hưởng, tạo động lực cho người khác.' },
        { id: 13, text: 'Đưa ra các quyết định chiến lược quan trọng cho tổ chức.' },
        { id: 14, text: 'Làm lãnh đạo trong một tổ chức, công ty.' },
    ],
  },
  {
    code: 'C',
    name: 'Conventional - Nhóm Quy củ',
    description: 'Những người thuộc nhóm này có khả năng làm việc với các con số, dữ liệu và làm theo các chỉ dẫn, quy trình có sẵn. Họ thích sự rõ ràng, chính xác và có tổ chức.',
    questions: [
        { id: 1, text: 'Làm việc với các con số, bảng tính excel, phần mềm kế toán.' },
        { id: 2, text: 'Sắp xếp hồ sơ, tài liệu, dữ liệu một cách có hệ thống.' },
        { id: 3, text: 'Làm các công việc đòi hỏi sự chính xác và chú ý đến từng chi tiết.' },
        { id: 4, text: 'Lập kế hoạch, theo dõi tiến độ dự án.' },
        { id: 5, text: 'Làm công việc về kế toán, kiểm toán, tài chính.' },
        { id: 6, text: 'Làm việc trong môi trường văn phòng, có quy củ, nề nếp.' },
        { id: 7, text: 'Tuân thủ các quy trình, quy định, chính sách của công ty.' },
        { id: 8, text: 'Kiểm tra, đối chiếu chứng từ, số liệu để đảm bảo không có sai sót.' },
        { id: 9, text: 'Nhập liệu, xử lý và quản lý cơ sở dữ liệu khách hàng, sản phẩm.' },
        { id: 10, text: 'Làm việc với các hệ thống phân loại, lưu trữ thông tin.' },
        { id: 11, text: 'Soạn thảo văn bản, hợp đồng, báo cáo theo mẫu có sẵn.' },
        { id: 12, text: 'Làm công việc có tính chất ổn định, lặp đi lặp lại.' },
        { id: 13, text: 'Làm thủ quỹ, quản lý dòng tiền, thực hiện các giao dịch ngân hàng.' },
        { id: 14, text: 'Làm các công việc hành chính, văn thư, hỗ trợ cho các bộ phận khác.' },
    ],
  },
];
