
export type JobDetail = {
    name: string;
    slug: string;
}

export type Industry = {
    name: string;
    slug: string;
    keywords: JobDetail[];
};

export const industriesByJobType: { [key: string]: Industry[] } = {
    'thuc-tap-sinh-ky-nang': [
      { name: 'Ngư nghiệp', slug: 'ngu-nghiep-tts', keywords: [
          { name: 'Câu cá ngừ cần và dây', slug: 'cau-ca-ngu-can-va-day' },
          { name: 'Câu mực', slug: 'cau-muc' },
          { name: 'Câu tôm, cua bằng lồng', slug: 'cau-tom-cua-bang-long' },
          { name: 'Đánh cá dây câu dài', slug: 'danh-ca-day-cau-dai' },
          { name: 'Đánh cá lưới kéo', slug: 'danh-ca-luoi-keo' },
          { name: 'Đánh cá lưới rê', slug: 'danh-ca-luoi-re' },
          { name: 'Đánh cá lưới sào', slug: 'danh-ca-luoi-sao' },
          { name: 'Đánh cá lưới thả', slug: 'danh-ca-luoi-tha' },
          { name: 'Đặt lưới đánh cá', slug: 'dat-luoi-danh-ca' },
          { name: 'Nuôi sò điệp', slug: 'nuoi-so-diep' }
      ] },
      { name: 'Nông nghiệp', slug: 'nong-nghiep-tts', keywords: [
          { name: 'Chăn nuôi bò', slug: 'chan-nuoi-bo' },
          { name: 'Chăn nuôi bò sữa', slug: 'chan-nuoi-bo-sua' },
          { name: 'Chăn nuôi gà', slug: 'chan-nuoi-ga' },
          { name: 'Chăn nuôi lợn', slug: 'chan-nuoi-lon' },
          { name: 'Nhặt trứng gà', slug: 'nhat-trung-ga' },
          { name: 'Nông nghiệp chăn nuôi', slug: 'nong-nghiep-chan-nuoi' },
          { name: 'Nông nghiệp trồng trọt', slug: 'nong-nghiep-trong-trot' },
          { name: 'Thu hoạch bắp cải', slug: 'thu-hoach-bap-cai' },
          { name: 'Thu hoạch cà chua', slug: 'thu-hoach-ca-chua' },
          { name: 'Thu hoạch dâu tây', slug: 'thu-hoach-dau-tay' },
          { name: 'Thu hoạch hoa', slug: 'thu-hoach-hoa' },
          { name: 'Thu hoạch hoa quả', slug: 'thu-hoach-hoa-qua' },
          { name: 'Thu hoạch rau củ', slug: 'thu-hoach-rau-cu' },
          { name: 'Trồng cây ăn quả', slug: 'trong-cay-an-qua' },
          { name: 'Trồng nấm', slug: 'trong-nam' },
          { name: 'Trồng nấm công nghệ cao', slug: 'trong-nam-cong-nghe-cao' },
          { name: 'Trồng rau củ', slug: 'trong-rau-cu' },
          { name: 'Trồng trọt nhà kính', slug: 'trong-trot-nha-kinh' }
      ] },
      { name: 'Thực phẩm', slug: 'thuc-pham-tts', keywords: [
          { name: 'Bánh gạo', slug: 'banh-gao' },
          { name: 'Bánh kẹo', slug: 'banh-keo' },
          { name: 'Bánh ngọt', slug: 'banh-ngot' },
          { name: 'Bếp viện', slug: 'bep-vien' },
          { name: 'Chế biến cá', slug: 'che-bien-ca' },
          { name: 'Chế biến đồ ăn sẵn', slug: 'che-bien-do-an-san' },
          { name: 'Chế biến gia cầm', slug: 'che-bien-gia-cam' },
          { name: 'Chế biến sushi', slug: 'che-bien-sushi' },
          { name: 'Chế biến thịt bò, lợn', slug: 'che-bien-thit-bo-lon' },
          { name: 'Chế biến thuỷ sản sống', slug: 'che-bien-thuy-san-song' },
          { name: 'Chiết xuất thuỷ sản', slug: 'chiet-xuat-thuy-san' },
          { name: 'Cơm hộp', slug: 'com-hop' },
          { name: 'Cơm nắm', slug: 'com-nam' },
          { name: 'Cửa hàng siêu thị', slug: 'cua-hang-sieu-thi' },
          { name: 'Đậu hũ', slug: 'dau-hu' },
          { name: 'Đồ ăn kèm', slug: 'do-an-kem' },
          { name: 'Đồ konbini', slug: 'do-konbini' },
          { name: 'Đóng gói bánh kẹo', slug: 'dong-goi-banh-keo' },
          { name: 'Đóng gói cafe', slug: 'dong-goi-cafe' },
          { name: 'Đóng gói gạo', slug: 'dong-goi-gao' },
          { name: 'Đóng gói rau', slug: 'dong-goi-rau' },
          { name: 'Đóng gói rau củ', slug: 'dong-goi-rau-cu' },
          { name: 'Đóng gói rong biển', slug: 'dong-goi-rong-bien' },
          { name: 'Đóng gói thanh cua', slug: 'dong-goi-thanh-cua' },
          { name: 'Đóng hộp thực phẩm', slug: 'dong-hop-thuc-pham' },
          { name: 'Gia công đồ ăn liền', slug: 'gia-cong-do-an-lien' },
          { name: 'Giăm bông, xúc xích...', slug: 'giam-bong-xuc-xich' },
          { name: 'Há cảo', slug: 'ha-cao' },
          { name: 'Làm bánh kẹo', slug: 'lam-banh-keo' },
          { name: 'Mỳ tôm', slug: 'my-tom' },
          { name: 'Salad', slug: 'salad' },
          { name: 'Sản xuất bánh mì', slug: 'san-xuat-banh-mi' },
          { name: 'Sản xuất dưa muối', slug: 'san-xuat-dua-muoi' },
          { name: 'Sản xuất mắm cá', slug: 'san-xuat-mam-ca' },
          { name: 'Sản xuất mỳ', slug: 'san-xuat-my' },
          { name: 'Siêu thị', slug: 'sieu-thi' },
          { name: 'Tẩm ướp thuỷ sản', slug: 'tam-uop-thuy-san' },
          { name: 'Thái cá sashimi', slug: 'thai-ca-sashimi' },
          { name: 'Thịt bò', slug: 'thit-bo' },
          { name: 'Thịt gà', slug: 'thit-ga' },
          { name: 'Thịt lợn', slug: 'thit-lon' },
          { name: 'Thức ăn cơ sở y tế', slug: 'thuc-an-co-so-y-te' },
          { name: 'Thực phẩm', slug: 'thuc-pham' },
          { name: 'Thực phẩm sữa', slug: 'thuc-pham-sua' },
          { name: 'Thực phẩm trứng', slug: 'thuc-pham-trung' },
          { name: 'Thuỷ sản gia công chế biến', slug: 'thuy-san-gia-cong-che-bien' },
          { name: 'Thuỷ sản khô', slug: 'thuy-san-kho' },
          { name: 'Thuỷ sản lên men', slug: 'thuy-san-len-men' },
          { name: 'Thuỷ sản sấy khô', slug: 'thuy-san-say-kho' },
          { name: 'Thuỷ sản ủ muối', slug: 'thuy-san-u-muoi' },
          { name: 'Thuỷ sản xông khói', slug: 'thuy-san-xong-khoi' }
      ] },
      { name: 'Sản xuất, dịch vụ tổng hợp', slug: 'san-xuat-dich-vu-tong-hop-tts', keywords: [
          { name: '(Khách sạn) Tiếp khách, quản lý vệ sinh', slug: 'khach-san-tiep-khach-quan-ly-ve-sinh' },
          { name: 'Bảo dưỡng ô tô', slug: 'bao-duong-o-to' },
          { name: 'Bảo trì đường sắt', slug: 'bao-tri-duong-sat' },
          { name: 'Buồng phòng khách sạn', slug: 'buong-phong-khach-san' },
          { name: 'Công việc cưa gỗ', slug: 'cong-viec-cua-go' },
          { name: 'Điều dưỡng, hộ lý', slug: 'dieu-duong-ho-ly' },
          { name: 'Dọn dẹp khoang hành khách', slug: 'don-dep-khoang-hanh-khach' },
          { name: 'Đóng gói', slug: 'dong-goi' },
          { name: 'Đóng gói công nghiệp', slug: 'dong-goi-cong-nghiep' },
          { name: 'Đóng gói mỹ phẩm', slug: 'dong-goi-my-pham' },
          { name: 'Đóng sách', slug: 'dong-sach' },
          { name: 'Đúc gốm bằng áp lực', slug: 'duc-gom-bang-ap-luc' },
          { name: 'Đúc khuôn cao su', slug: 'duc-khuon-cao-su' },
          { name: 'Đục lỗ hộp in', slug: 'duc-lo-hop-in' },
          { name: 'Đúc nhựa', slug: 'duc-nhua' },
          { name: 'Đúc nhựa cán xếp chồng', slug: 'duc-nhua-can-xep-chong' },
          { name: 'Đục nhựa ép phun', slug: 'duc-nhua-ep-phun' },
          { name: 'Đúc nhựa nén', slug: 'duc-nhua-nen' },
          { name: 'Đúc nhựa thổi định hình', slug: 'duc-nhua-thoi-dinh-hinh' },
          { name: 'Đúc nhựa thổi phồng', slug: 'duc-nhua-thoi-phong' },
          { name: 'Gia công đồ gia dụng', slug: 'gia-cong-do-gia-dung' },
          { name: 'Gia công ép đùn cao su', slug: 'gia-cong-ep-dun-cao-su' },
          { name: 'Gia công sản phẩm gỗ', slug: 'gia-cong-san-pham-go' },
          { name: 'Gỗ ép', slug: 'go-ep' },
          { name: 'Hàng hóa hàng không', slug: 'hang-hoa-hang-khong' },
          { name: 'Hỗ trợ mặt đất máy bay', slug: 'ho-tro-mat-dat-may-bay' },
          { name: 'In gốm', slug: 'in-gom' },
          { name: 'In offset', slug: 'in-offset' },
          { name: 'In ống đồng', slug: 'in-ong-dong' },
          { name: 'In vỏ bánh kẹo', slug: 'in-vo-banh-keo' },
          { name: 'Kiểm tra linh kiện ô tô', slug: 'kiem-tra-linh-kien-o-to' },
          { name: 'Kiểm tra sản phẩm nhựa', slug: 'kiem-tra-san-pham-nhua' },
          { name: 'Lắp ráp linh kiện ô tô', slug: 'lap-rap-linh-kien-o-to' },
          { name: 'Linh kiện ô tô', slug: 'linh-kien-o-to' },
          { name: 'Nặn gốm bằng bánh xoay', slug: 'nan-gom-bang-banh-xoay' },
          { name: 'Nhiên liệu rắn từ rác', slug: 'nhien-lieu-ran-tu-rac' },
          { name: 'Sản xuất hộp bìa cứng', slug: 'san-xuat-hop-bia-cung' },
          { name: 'Sản xuất hộp in', slug: 'san-xuat-hop-in' },
          { name: 'Sản xuất hộp nhãn dán', slug: 'san-xuat-hop-nhan-dan' },
          { name: 'Sản xuất linh kiện', slug: 'san-xuat-linh-kien' },
          { name: 'Sản xuất pin năng lượng', slug: 'san-xuat-pin-nang-luong' },
          { name: 'Sản xuất vải lanh', slug: 'san-xuat-vai-lanh' },
          { name: 'Sửa chữa ô tô', slug: 'sua-chua-o-to' },
          { name: 'Thiết bị khí nén đường sắt', slug: 'thiet-bi-khi-nen-duong-sat' },
          { name: 'Trộn và cán cao su', slug: 'tron-va-can-cao-su' },
          { name: 'Vật liệu composite nhiều lớp', slug: 'vat-lieu-composite-nhieu-lop' },
          { name: 'Vệ sinh phòng học', slug: 've-sinh-phong-hoc' },
          { name: 'Vệ sinh toà nhà', slug: 've-sinh-toa-nha' },
          { name: 'Vệ sinh văn phòng', slug: 've-sinh-van-phong' }
      ] },
      { name: 'Cơ khí, kim loại', slug: 'co-khi-kim-loai-tts', keywords: [
          { name: 'Bản mạch in', slug: 'ban-mach-in' },
          { name: 'Bảo trì máy móc', slug: 'bao-tri-may-moc' },
          { name: 'Chế tạo kim loại tấm', slug: 'che-tao-kim-loai-tam' },
          { name: 'Chế tạo máy', slug: 'che-tao-may' },
          { name: 'Cơ khí', slug: 'co-khi' },
          { name: 'Cuộn dây máy điện quay', slug: 'cuon-day-may-dien-quay' },
          { name: 'Dập khuôn kim loại', slug: 'dap-khuon-kim-loai' },
          { name: 'Điện', slug: 'dien' },
          { name: 'Điện tử', slug: 'dien-tu' },
          { name: 'Đóng tàu', slug: 'dong-tau' },
          { name: 'Đúc', slug: 'duc' },
          { name: 'Đúc gang', slug: 'duc-gang' },
          { name: 'Đúc khuôn', slug: 'duc-khuon' },
          { name: 'Đúc khuôn buồng lạnh', slug: 'duc-khuon-buong-lanh' },
          { name: 'Đúc khuôn buồng nóng', slug: 'duc-khuon-buong-nong' },
          { name: 'Đúc kim loại màu', slug: 'duc-kim-loai-mau' },
          { name: 'Ép dập kim loại', slug: 'ep-dap-kim-loai' },
          { name: 'Gia công cơ khí', slug: 'gia-cong-co-khi' },
          { name: 'Gia công ép đùn', slug: 'gia-cong-ep-dun' },
          { name: 'Gia công kim loại - Tekko', slug: 'gia-cong-kim-loai-tekko' },
          { name: 'Gia công tinh', slug: 'gia-cong-tinh' },
          { name: 'Hàn', slug: 'han' },
          { name: 'Hàn bán tự động', slug: 'han-ban-tu-dong' },
          { name: 'Hàn kết cấu', slug: 'han-ket-cau' },
          { name: 'Hàn khí', slug: 'han-khi' },
          { name: 'Hàn khung thép', slug: 'han-khung-thep' },
          { name: 'Hàn tàu', slug: 'han-tau' },
          { name: 'Hàn thủ công', slug: 'han-thu-cong' },
          { name: 'Hàn tủ điện', slug: 'han-tu-dien' },
          { name: 'Hàn xì', slug: 'han-xi' },
          { name: 'Hoàn thiện dụng cụ nung chảy', slug: 'hoan-thien-dung-cu-nung-chay' },
          { name: 'Hoàn thiện khuôn', slug: 'hoan-thien-khuon' },
          { name: 'Hoàn thiện sản phẩm ép đùn', slug: 'hoan-thien-san-pham-ep-dun' },
          { name: 'Kiểm tra máy móc', slug: 'kiem-tra-may-moc' },
          { name: 'Lắp đặt điều hoà', slug: 'lap-dat-dieu-hoa' },
          { name: 'Lắp đặt máy móc', slug: 'lap-dat-may-moc' },
          { name: 'Lắp đặt tủ lạnh', slug: 'lap-dat-tu-lanh' },
          { name: 'Lắp ráp điện', slug: 'lap-rap-dien' },
          { name: 'Lắp ráp điện tử', slug: 'lap-rap-dien-tu' },
          { name: 'Lắp ráp linh kiện bán dẫn', slug: 'lap-rap-linh-kien-ban-dan' },
          { name: 'Lắp ráp máy biến áp', slug: 'lap-rap-may-bien-ap' },
          { name: 'Lắp ráp thiết bị điện khí', slug: 'lap-rap-thiet-bi-dien-khi' },
          { name: 'Lắp ráp thiết bị điện quay', slug: 'lap-rap-thiet-bi-dien-quay' },
          { name: 'Lắp ráp thiết bị điện tử', slug: 'lap-rap-thiet-bi-dien-tu' },
          { name: 'Lắp thiết bị đóng, mở', slug: 'lap-thiet-bi-dong-mo' },
          { name: 'Lắp tủ điện, tủ điều khiển', slug: 'lap-tu-dien-tu-dieu-khien' },
          { name: 'Mạ điện', slug: 'ma-dien' },
          { name: 'Mạ kẽm nhúng nóng', slug: 'ma-kem-nhung-nong' },
          { name: 'Máy sản xuất tấm kim loại', slug: 'may-san-xuat-tam-kim-loai' },
          { name: 'Rèn', slug: 'ren' },
          { name: 'Rèn bằng búa', slug: 'ren-bang-bua' },
          { name: 'Sơn', slug: 'son' },
          { name: 'Sơn cầu thép', slug: 'son-cau-thep' },
          { name: 'Sơn công trình xây dựng', slug: 'son-cong-trinh-xay-dung' },
          { name: 'Sơn kim loại', slug: 'son-kim-loai' },
          { name: 'Sơn phun', slug: 'son-phun' },
          { name: 'Sử dụng máy phay', slug: 'su-dung-may-phay' },
          { name: 'Sử dụng máy tiện số', slug: 'su-dung-may-tien-so' },
          { name: 'Sử dụng máy tiện thường', slug: 'su-dung-may-tien-thuong' },
          { name: 'Thi công điện', slug: 'thi-cong-dien' },
          { name: 'Thi công kết cấu thép', slug: 'thi-cong-ket-cau-thep' },
          { name: 'Thiết kế bảng mạch in', slug: 'thiet-ke-bang-mach-in' },
          { name: 'Vận hành máy', slug: 'van-hanh-may' },
          { name: 'Vận hành máy CNC', slug: 'van-hanh-may-cnc' },
          { name: 'Vận hành máy ép', slug: 'van-hanh-may-ep' },
          { name: 'Vận hành máy ép nhựa', slug: 'van-hanh-may-ep-nhua' },
          { name: 'Vận hành robot', slug: 'van-hanh-robot' },
          { name: 'Xử lý điện hóa nhôm', slug: 'xu-ly-dien-hoa-nhom' }
      ] },
      { name: 'Xây dựng', slug: 'xay-dung-tts', keywords: [
          { name: 'Bê tông', slug: 'be-tong' },
          { name: 'Buộc thép', slug: 'buoc-thep' },
          { name: 'Chống thấm', slug: 'chong-tham' },
          { name: 'Cốp pha công trình', slug: 'cop-pha-cong-trinh' },
          { name: 'Dán tường', slug: 'dan-tuong' },
          { name: 'Đổ bê tông áp lực', slug: 'do-be-tong-ap-luc' },
          { name: 'Đổ nhựa đường', slug: 'do-nhua-duong' },
          { name: 'Dựng giàn giáo', slug: 'dung-gian-giao' },
          { name: 'Đường ống', slug: 'duong-ong' },
          { name: 'Đường ống điều hoà', slug: 'duong-ong-dieu-hoa' },
          { name: 'Đường ống nhà máy', slug: 'duong-ong-nha-may' },
          { name: 'Đường ống nước', slug: 'duong-ong-nuoc' },
          { name: 'Đường ống xây dựng', slug: 'duong-ong-xay-dung' },
          { name: 'Gia công đường ống', slug: 'gia-cong-duong-ong' },
          { name: 'Gia công khung thép', slug: 'gia-cong-khung-thep' },
          { name: 'Gia công khung thép trong xưởng', slug: 'gia-cong-khung-thep-trong-xuong' },
          { name: 'Gia công sắt trong xưởng', slug: 'gia-cong-sat-trong-xuong' },
          { name: 'Gia công vật liệu đá', slug: 'gia-cong-vat-lieu-da' },
          { name: 'Hàn khung thép trên cao', slug: 'han-khung-thep-tren-cao' },
          { name: 'Hoàn thiện nội thất', slug: 'hoan-thien-noi-that' },
          { name: 'Hoàn thiện sàn nhựa', slug: 'hoan-thien-san-nhua' },
          { name: 'Hoàn thiện sàn thảm', slug: 'hoan-thien-san-tham' },
          { name: 'Hoàn thiện ván', slug: 'hoan-thien-van' },
          { name: 'Hút nước ngầm công trình', slug: 'hut-nuoc-ngam-cong-trinh' },
          { name: 'Khoan giếng máy dập', slug: 'khoan-gieng-may-dap' },
          { name: 'Khoan giếng máy khoan', slug: 'khoan-gieng-may-khoan' },
          { name: 'Khung chắn toà nhà', slug: 'khung-chan-toa-nha' },
          { name: 'Lái máy ủi', slug: 'lai-may-ui' },
          { name: 'Lái máy xây dựng', slug: 'lai-may-xay-dung' },
          { name: 'Lái máy xúc', slug: 'lai-may-xuc' },
          { name: 'Lái máy xúc lật', slug: 'lai-may-xuc-lat' },
          { name: 'Lái xe lu', slug: 'lai-xe-lu' },
          { name: 'Làm nền, móng', slug: 'lam-nen-mong' },
          { name: 'Lắp bồn tắm', slug: 'lap-bon-tam' },
          { name: 'Lắp đặt đường ống', slug: 'lap-dat-duong-ong' },
          { name: 'Lắp đặt lò nung-xây dựng', slug: 'lap-dat-lo-nung-xay-dung' },
          { name: 'Lắp đặt pin năng lượng', slug: 'lap-dat-pin-nang-luong' },
          { name: 'Lắp điện lạnh, điều hòa', slug: 'lap-dien-lanh-dieu-hoa' },
          { name: 'Lắp ghép cốt thép', slug: 'lap-ghep-cot-thep' },
          { name: 'Lát đá', slug: 'lat-da' },
          { name: 'Lợp mái nhà', slug: 'lop-mai-nha' },
          { name: 'Lợp ngói', slug: 'lop-ngoi' },
          { name: 'Mộc cốp pha', slug: 'moc-cop-pha' },
          { name: 'Nội thất gỗ-xây dựng', slug: 'noi-that-go-xay-dung' },
          { name: 'Ốp lát gạch', slug: 'op-lat-gach' },
          { name: 'Phá dỡ', slug: 'pha-do' },
          { name: 'San lấp mặt bằng', slug: 'san-lap-mat-bang' },
          { name: 'Sản xuất bê tông', slug: 'san-xuat-be-tong' },
          { name: 'Sơn xây dựng', slug: 'son-xay-dung' },
          { name: 'Tấm kim loại kiến trúc', slug: 'tam-kim-loai-kien-truc' },
          { name: 'Tấm kim loại ống gió', slug: 'tam-kim-loai-ong-gio' },
          { name: 'Thi công dán tường', slug: 'thi-cong-dan-tuong' },
          { name: 'Thi công lắp rèm', slug: 'thi-cong-lap-rem' },
          { name: 'Thi công móng thép', slug: 'thi-cong-mong-thep' },
          { name: 'Thợ mộc xây dựng', slug: 'tho-moc-xay-dung' },
          { name: 'Trát vữa', slug: 'trat-vua' },
          { name: 'Xây dựng tổng hợp', slug: 'xay-dung-tong-hop' }
      ] },
      { name: 'May mặc', slug: 'may-mac-tts', keywords: [
          { name: 'Chăn ga gối đệm', slug: 'chan-ga-goi-dem' },
          { name: 'Công việc trước kéo sợi', slug: 'cong-viec-truoc-keo-soi' },
          { name: 'Công việc trước khi dệt', slug: 'cong-viec-truoc-khi-det' },
          { name: 'Dệt hoàn thiện', slug: 'det-hoan-thien' },
          { name: 'Dệt kim máy sợi dọc', slug: 'det-kim-may-soi-doc' },
          { name: 'Dệt may', slug: 'det-may' },
          { name: 'Gia công dệt', slug: 'gia-cong-det' },
          { name: 'Gia công sợi hỗn hợp', slug: 'gia-cong-soi-hon-hop' },
          { name: 'Kéo sợi tinh', slug: 'keo-soi-tinh' },
          { name: 'May khăn mặt', slug: 'may-khan-mat' },
          { name: 'May mặc', slug: 'may-mac' },
          { name: 'May quần áo', slug: 'may-quan-ao' },
          { name: 'May quần áo nam', slug: 'may-quan-ao-nam' },
          { name: 'Nhuộm chỉ', slug: 'nhuom-chi' },
          { name: 'Nhuộm vải, đan len', slug: 'nhuom-vai-dan-len' },
          { name: 'Quần áo phụ nữ, trẻ em', slug: 'quan-ao-phu-nu-tre-em' },
          { name: 'Quấn sợi', slug: 'quan-soi' },
          { name: 'Sản xuất áo sơ mi', slug: 'san-xuat-ao-so-mi' },
          { name: 'Sản xuất đồ lót', slug: 'san-xuat-do-lot' },
          { name: 'Sản xuất ghế ngồi ô tô', slug: 'san-xuat-ghe-ngoi-o-to' },
          { name: 'Sản xuất máy dệt kim tròn', slug: 'san-xuat-may-det-kim-tron' },
          { name: 'Sản xuất tất', slug: 'san-xuat-tat' },
          { name: 'Sản xuất thảm dệt', slug: 'san-xuat-tham-det' },
          { name: 'Sản xuất thảm đục lỗ', slug: 'san-xuat-tham-duc-lo' },
          { name: 'Sản xuất thảm nhung nổi', slug: 'san-xuat-tham-nhung-noi' },
          { name: 'Sản xuất vải bạt', slug: 'san-xuat-vai-bat' }
      ] }
    ],
    'ky-nang-dac-dinh': [
      { name: 'Ngư nghiệp', slug: 'ngu-nghiep-tokutei', keywords: [
          { name: 'Nuôi trồng thủy sản', slug: 'nuoi-trong-thuy-san' },
          { name: 'Đánh bắt cá', slug: 'danh-bat-ca' }
      ] },
      { name: 'Nông nghiệp', slug: 'nong-nghiep-tokutei', keywords: [
          { name: 'Chăn nuôi bò', slug: 'chan-nuoi-bo' },
          { name: 'Chăn nuôi bò sữa', slug: 'chan-nuoi-bo-sua' },
          { name: 'Chăn nuôi gà', slug: 'chan-nuoi-ga' },
          { name: 'Chăn nuôi lợn', slug: 'chan-nuoi-lon' },
          { name: 'Nhặt trứng gà', slug: 'nhat-trung-ga' },
          { name: 'Trồng cây ăn quả', slug: 'trong-cay-an-qua' },
          { name: 'Trồng hoa', slug: 'trong-hoa' },
          { name: 'Trồng nấm', slug: 'trong-nam' },
          { name: 'Trồng rau củ quả trong nhà kính', slug: 'trong-rau-cu-qua-trong-nha-kinh' },
          { name: 'Trồng rau củ quả ngoài trời', slug: 'trong-rau-cu-qua-ngoai-troi' }
      ] },
      { name: 'Nhà hàng', slug: 'nha-hang-tokutei', keywords: [
          { name: 'Chạy bàn', slug: 'chay-ban' },
          { name: 'Mua hàng', slug: 'mua-hang' },
          { name: 'Nấu bếp', slug: 'nau-bep' },
          { name: 'Nhà hàng', slug: 'nha-hang' },
          { name: 'Phụ bếp', slug: 'phu-bep' },
          { name: 'Quản lý', slug: 'quan-ly' },
          { name: 'Rửa bát', slug: 'rua-bat' },
          { name: 'Thu ngân', slug: 'thu-ngan' }
      ] },
      { name: 'Thực phẩm', slug: 'thuc-pham-tokutei', keywords: [
          { name: 'Bánh gạo', slug: 'banh-gao' },
          { name: 'Bánh kẹo', slug: 'banh-keo' },
          { name: 'Bánh ngọt', slug: 'banh-ngot' },
          { name: 'Bếp viện', slug: 'bep-vien' },
          { name: 'Chế biến cá', slug: 'che-bien-ca' },
          { name: 'Chế biến đồ ăn sẵn', slug: 'che-bien-do-an-san' },
          { name: 'Chế biến gia cầm', slug: 'che-bien-gia-cam' },
          { name: 'Chế biến sushi', slug: 'che-bien-sushi' },
          { name: 'Chế biến thịt bò, lợn', slug: 'che-bien-thit-bo-lon' },
          { name: 'Chế biến thuỷ sản sống', slug: 'che-bien-thuy-san-song' },
          { name: 'Chiết xuất thuỷ sản', slug: 'chiet-xuat-thuy-san' },
          { name: 'Cơm hộp', slug: 'com-hop' },
          { name: 'Cơm nắm', slug: 'com-nam' },
          { name: 'Cửa hàng siêu thị', slug: 'cua-hang-sieu-thi' },
          { name: 'Đậu hũ', slug: 'dau-hu' },
          { name: 'Đồ ăn kèm', slug: 'do-an-kem' },
          { name: 'Đồ konbini', slug: 'do-konbini' },
          { name: 'Đóng gói bánh kẹo', slug: 'dong-goi-banh-keo' },
          { name: 'Đóng gói cafe', slug: 'dong-goi-cafe' },
          { name: 'Đóng gói gạo', slug: 'dong-goi-gao' },
          { name: 'Đóng gói rau', slug: 'dong-goi-rau' },
          { name: 'Đóng gói rau củ', slug: 'dong-goi-rau-cu' },
          { name: 'Đóng gói rong biển', slug: 'dong-goi-rong-bien' },
          { name: 'Đóng gói thanh cua', slug: 'dong-goi-thanh-cua' },
          { name: 'Đóng hộp thực phẩm', slug: 'dong-hop-thuc-pham' },
          { name: 'Gia công đồ ăn liền', slug: 'gia-cong-do-an-lien' },
          { name: 'Giăm bông, xúc xích...', slug: 'giam-bong-xuc-xich' },
          { name: 'Há cảo', slug: 'ha-cao' },
          { name: 'Làm bánh kẹo', slug: 'lam-banh-keo' },
          { name: 'Mỳ tôm', slug: 'my-tom' },
          { name: 'Salad', slug: 'salad' },
          { name: 'Sản xuất bánh mì', slug: 'san-xuat-banh-mi' },
          { name: 'Sản xuất dưa muối', slug: 'san-xuat-dua-muoi' },
          { name: 'Sản xuất mắm cá', slug: 'san-xuat-mam-ca' },
          { name: 'Sản xuất mỳ', slug: 'san-xuat-my' },
          { name: 'Siêu thị', slug: 'sieu-thi' },
          { name: 'Tẩm ướp thuỷ sản', slug: 'tam-uop-thuy-san' },
          { name: 'Thái cá sashimi', slug: 'thai-ca-sashimi' },
          { name: 'Thịt bò', slug: 'thit-bo' },
          { name: 'Thịt gà', slug: 'thit-ga' },
          { name: 'Thịt lợn', slug: 'thit-lon' },
          { name: 'Thức ăn cơ sở y tế', slug: 'thuc-an-co-so-y-te' },
          { name: 'Thực phẩm', slug: 'thuc-pham' },
          { name: 'Thực phẩm sữa', slug: 'thuc-pham-sua' },
          { name: 'Thực phẩm trứng', slug: 'thuc-pham-trung' },
          { name: 'Thuỷ sản gia công chế biến', slug: 'thuy-san-gia-cong-che-bien' },
          { name: 'Thuỷ sản khô', slug: 'thuy-san-kho' },
          { name: 'Thuỷ sản lên men', slug: 'thuy-san-len-men' },
          { name: 'Thuỷ sản sấy khô', slug: 'thuy-san-say-kho' },
          { name: 'Thuỷ sản ủ muối', slug: 'thuy-san-u-muoi' },
          { name: 'Thuỷ sản xông khói', slug: 'thuy-san-xong-khoi' }
      ] },
      { name: 'Sản xuất, dịch vụ tổng hợp', slug: 'san-xuat-dich-vu-tong-hop-tokutei', keywords: [
          { name: 'Bảo dưỡng ô tô', slug: 'bao-duong-o-to' },
          { name: 'Công việc cưa gỗ', slug: 'cong-viec-cua-go' },
          { name: 'Đóng gói', slug: 'dong-goi' },
          { name: 'Đóng gói công nghiệp', slug: 'dong-goi-cong-nghiep' },
          { name: 'Đóng gói mỹ phẩm', slug: 'dong-goi-my-pham' },
          { name: 'Đóng sách', slug: 'dong-sach' },
          { name: 'Đúc gốm bằng áp lực', slug: 'duc-gom-bang-ap-luc' },
          { name: 'Đúc khuôn cao su', slug: 'duc-khuon-cao-su' },
          { name: 'Đục lỗ hộp in', slug: 'duc-lo-hop-in' },
          { name: 'Đúc nhựa', slug: 'duc-nhua' },
          { name: 'Đúc nhựa cán xếp chồng', slug: 'duc-nhua-can-xep-chong' },
          { name: 'Đục nhựa ép phun', slug: 'duc-nhua-ep-phun' },
          { name: 'Đúc nhựa nén', slug: 'duc-nhua-nen' },
          { name: 'Đúc nhựa thổi định hình', slug: 'duc-nhua-thoi-dinh-hinh' },
          { name: 'Đúc nhựa thổi phồng', slug: 'duc-nhua-thoi-phong' },
          { name: 'Gia công đồ gia dụng', slug: 'gia-cong-do-gia-dung' },
          { name: 'Gia công ép đùn cao su', slug: 'gia-cong-ep-dun-cao-su' },
          { name: 'Gia công sản phẩm gỗ', slug: 'gia-cong-san-pham-go' },
          { name: 'Gỗ ép', slug: 'go-ep' },
          { name: 'In gốm', slug: 'in-gom' },
          { name: 'In offset', slug: 'in-offset' },
          { name: 'In ống đồng', slug: 'in-ong-dong' },
          { name: 'In vỏ bánh kẹo', slug: 'in-vo-banh-keo' },
          { name: 'Kiểm tra sản phẩm nhựa', slug: 'kiem-tra-san-pham-nhua' },
          { name: 'Nặn gốm bằng bánh xoay', slug: 'nan-gom-bang-banh-xoay' },
          { name: 'Nhiên liệu rắn từ rác', slug: 'nhien-lieu-ran-tu-rac' },
          { name: 'Sản xuất hộp bìa cứng', slug: 'san-xuat-hop-bia-cung' },
          { name: 'Sản xuất hộp in', slug: 'san-xuat-hop-in' },
          { name: 'Sản xuất hộp nhãn dán', slug: 'san-xuat-hop-nhan-dan' },
          { name: 'Sản xuất linh kiện', slug: 'san-xuat-linh-kien' },
          { name: 'Sản xuất pin năng lượng', slug: 'san-xuat-pin-nang-luong' },
          { name: 'Sản xuất vải lanh', slug: 'san-xuat-vai-lanh' },
          { name: 'Sửa chữa ô tô', slug: 'sua-chua-o-to' },
          { name: 'Thiết bị khí nén đường sắt', slug: 'thiet-bi-khi-nen-duong-sat' },
          { name: 'Trộn và cán cao su', slug: 'tron-va-can-cao-su' },
          { name: 'Vật liệu composite nhiều lớp', slug: 'vat-lieu-composite-nhieu-lop' }
      ] },
      { name: 'Điện, điện tử', slug: 'dien-dien-tu-tokutei', keywords: [
          { name: 'Bản mạch in', slug: 'ban-mach-in' },
          { name: 'Cuộn dây máy điện quay', slug: 'cuon-day-may-dien-quay' },
          { name: 'Điện', slug: 'dien' },
          { name: 'Điện tử', slug: 'dien-tu' },
          { name: 'Lắp ráp điện', slug: 'lap-rap-dien' },
          { name: 'Lắp ráp điện tử', slug: 'lap-rap-dien-tu' },
          { name: 'Lắp ráp linh kiện bán dẫn', slug: 'lap-rap-linh-kien-ban-dan' },
          { name: 'Lắp ráp máy biến áp', slug: 'lap-rap-may-bien-ap' },
          { name: 'Lắp ráp thiết bị điện khí', slug: 'lap-rap-thiet-bi-dien-khi' },
          { name: 'Lắp ráp thiết bị điện quay', slug: 'lap-rap-thiet-bi-dien-quay' },
          { name: 'Lắp ráp thiết bị điện tử', slug: 'lap-rap-thiet-bi-dien-tu' },
          { name: 'Lắp thiết bị đóng, mở', slug: 'lap-thiet-bi-dong-mo' },
          { name: 'Lắp tủ điện, tủ điều khiển', slug: 'lap-tu-dien-tu-dieu-khien' },
          { name: 'Sản xuất bảng mạch in', slug: 'san-xuat-bang-mach-in' },
          { name: 'Sửa chữa dụng cụ', slug: 'sua-chua-dung-cu' },
          { name: 'Sửa chữa tủ điện', slug: 'sua-chua-tu-dien' },
          { name: 'Thi công điện', slug: 'thi-cong-dien' },
          { name: 'Thiết kế bảng mạch in', slug: 'thiet-ke-bang-mach-in' }
      ] },
      { name: 'Chế tạo Vật liệu', slug: 'che-tao-vat-lieu-tokutei', keywords: [
          { name: 'Xử lý nhiệt bề mặt', slug: 'xu-ly-nhiet-be-mat' },
          { name: 'Xử lý nhiệt một phần', slug: 'xu-ly-nhiet-mot-phan' },
          { name: 'Xử lý nhiệt tổng thể', slug: 'xu-ly-nhiet-tong-the' }
      ] },
      { name: 'Cơ khí, chế tạo máy', slug: 'co-khi-che-tao-may-tokutei', keywords: [
          { name: 'Bảo trì máy móc', slug: 'bao-tri-may-moc' },
          { name: 'Chế tạo kim loại tấm', slug: 'che-tao-kim-loai-tam' },
          { name: 'Chế tạo máy', slug: 'che-tao-may' },
          { name: 'Cơ khí', slug: 'co-khi' },
          { name: 'Dập khuôn kim loại', slug: 'dap-khuon-kim-loai' },
          { name: 'Đóng tàu', slug: 'dong-tau' },
          { name: 'Đúc', slug: 'duc' },
          { name: 'Đúc gang', slug: 'duc-gang' },
          { name: 'Đúc khuôn', slug: 'duc-khuon' },
          { name: 'Đúc khuôn buồng lạnh', slug: 'duc-khuon-buong-lanh' },
          { name: 'Đúc khuôn buồng nóng', slug: 'duc-khuon-buong-nong' },
          { name: 'Đúc kim loại màu', slug: 'duc-kim-loai-mau' },
          { name: 'Ép dập kim loại', slug: 'ep-dap-kim-loai' },
          { name: 'Gia công cơ khí', slug: 'gia-cong-co-khi' },
          { name: 'Gia công ép đùn', slug: 'gia-cong-ep-dun' },
          { name: 'Gia công kim loại - Tekko', slug: 'gia-cong-kim-loai-tekko' },
          { name: 'Gia công tinh', slug: 'gia-cong-tinh' },
          { name: 'Hàn', slug: 'han' },
          { name: 'Hàn bán tự động', slug: 'han-ban-tu-dong' },
          { name: 'Hàn kết cấu', slug: 'han-ket-cau' },
          { name: 'Hàn khí', slug: 'han-khi' },
          { name: 'Hàn khung thép', slug: 'han-khung-thep' },
          { name: 'Hàn tàu', slug: 'han-tau' },
          { name: 'Hàn thủ công', slug: 'han-thu-cong' },
          { name: 'Hàn tủ điện', slug: 'han-tu-dien' },
          { name: 'Hàn xì', slug: 'han-xi' },
          { name: 'Hoàn thiện dụng cụ nung chảy', slug: 'hoan-thien-dung-cu-nung-chay' },
          { name: 'Hoàn thiện khuôn', slug: 'hoan-thien-khuon' },
          { name: 'Hoàn thiện sản phẩm ép đùn', slug: 'hoan-thien-san-pham-ep-dun' },
          { name: 'Kiểm tra máy móc', slug: 'kiem-tra-may-moc' },
          { name: 'Lắp đặt điều hoà', slug: 'lap-dat-dieu-hoa' },
          { name: 'Lắp đặt máy móc', slug: 'lap-dat-may-moc' },
          { name: 'Lắp đặt tủ lạnh', slug: 'lap-dat-tu-lanh' },
          { name: 'Lắp ráp máy móc', slug: 'lap-rap-may-moc' },
          { name: 'Máy sản xuất tấm kim loại', slug: 'may-san-xuat-tam-kim-loai' },
          { name: 'Rèn', slug: 'ren' },
          { name: 'Rèn bằng búa', slug: 'ren-bang-bua' },
          { name: 'Sơn', slug: 'son' },
          { name: 'Sơn cầu thép', slug: 'son-cau-thep' },
          { name: 'Sơn công trình xây dựng', slug: 'son-cong-trinh-xay-dung' },
          { name: 'Sơn kim loại', slug: 'son-kim-loai' },
          { name: 'Sơn phun', slug: 'son-phun' },
          { name: 'Sử dụng máy phay', slug: 'su-dung-may-phay' },
          { name: 'Sử dụng máy tiện số', slug: 'su-dung-may-tien-so' },
          { name: 'Sử dụng máy tiện thường', slug: 'su-dung-may-tien-thuong' },
          { name: 'Thi công kết cấu thép', slug: 'thi-cong-ket-cau-thep' },
          { name: 'Vận hành máy', slug: 'van-hanh-may' },
          { name: 'Vận hành máy CNC', slug: 'van-hanh-may-cnc' },
          { name: 'Vận hành máy ép', slug: 'van-hanh-may-ep' },
          { name: 'Vận hành máy ép nhựa', slug: 'van-hanh-may-ep-nhua' },
          { name: 'Vận hành robot', slug: 'van-hanh-robot' },
          { name: 'Xử lý điện hóa nhôm', slug: 'xu-ly-dien-hoa-nhom' }
      ] },
      { name: 'Ô tô', slug: 'o-to-tokutei', keywords: [
          { name: 'Bảo dưỡng ô tô', slug: 'bao-duong-o-to' },
          { name: 'Kiểm tra linh kiện ô tô', slug: 'kiem-tra-linh-kien-o-to' },
          { name: 'Lắp ráp linh kiện ô tô', slug: 'lap-rap-linh-kien-o-to' },
          { name: 'Linh kiện ô tô', slug: 'linh-kien-o-to' },
          { name: 'Sửa chữa ô tô', slug: 'sua-chua-o-to' }
      ] },
      { name: 'Hàng không', slug: 'hang-khong-tokutei', keywords: [
          { name: 'hàng không', slug: 'hang-khong' },
          { name: 'sân bay', slug: 'san-bay' },
          { name: 'bốc dỡ', slug: 'boc-do' }
      ] },
      { name: 'Vận tải', slug: 'van-tai-tokutei', keywords: [
          { name: 'Hậu cần vận tải', slug: 'hau-can-van-tai' },
          { name: 'Lái xe', slug: 'lai-xe' },
          { name: 'Lái xe buýt', slug: 'lai-xe-buyt' },
          { name: 'Lái xe tải', slug: 'lai-xe-tai' },
          { name: 'Phụ xe', slug: 'phu-xe' },
          { name: 'Quản lý kho vận tải', slug: 'quan-ly-kho-van-tai' },
          { name: 'Thực tập lái xe', slug: 'thuc-tap-lai-xe' }
      ] },
      { name: 'Xây dựng', slug: 'xay-dung-tokutei', keywords: [
          { name: 'Bê tông', slug: 'be-tong' },
          { name: 'Buộc thép', slug: 'buoc-thep' },
          { name: 'Chống thấm', slug: 'chong-tham' },
          { name: 'Cốp pha công trình', slug: 'cop-pha-cong-trinh' },
          { name: 'Dán tường', slug: 'dan-tuong' },
          { name: 'Đổ bê tông áp lực', slug: 'do-be-tong-ap-luc' },
          { name: 'Đổ nhựa đường', slug: 'do-nhua-duong' },
          { name: 'Dựng giàn giáo', slug: 'dung-gian-giao' },
          { name: 'Đường ống', slug: 'duong-ong' },
          { name: 'Đường ống điều hoà', slug: 'duong-ong-dieu-hoa' },
          { name: 'Đường ống nhà máy', slug: 'duong-ong-nha-may' },
          { name: 'Đường ống nước', slug: 'duong-ong-nuoc' },
          { name: 'Đường ống xây dựng', slug: 'duong-ong-xay-dung' },
          { name: 'Gia công đường ống', slug: 'gia-cong-duong-ong' },
          { name: 'Gia công khung thép', slug: 'gia-cong-khung-thep' },
          { name: 'Gia công khung thép trong xưởng', slug: 'gia-cong-khung-thep-trong-xuong' },
          { name: 'Gia công sắt trong xưởng', slug: 'gia-cong-sat-trong-xuong' },
          { name: 'Gia công vật liệu đá', slug: 'gia-cong-vat-lieu-da' },
          { name: 'Hàn khung thép trên cao', slug: 'han-khung-thep-tren-cao' },
          { name: 'Hoàn thiện nội thất', slug: 'hoan-thien-noi-that' },
          { name: 'Hoàn thiện sàn nhựa', slug: 'hoan-thien-san-nhua' },
          { name: 'Hoàn thiện sàn thảm', slug: 'hoan-thien-san-tham' },
          { name: 'Hoàn thiện ván', slug: 'hoan-thien-van' },
          { name: 'Hút nước ngầm công trình', slug: 'hut-nuoc-ngam-cong-trinh' },
          { name: 'Khoan giếng máy dập', slug: 'khoan-gieng-may-dap' },
          { name: 'Khoan giếng máy khoan', slug: 'khoan-gieng-may-khoan' },
          { name: 'Khung chắn toà nhà', slug: 'khung-chan-toa-nha' },
          { name: 'Lái máy ủi', slug: 'lai-may-ui' },
          { name: 'Lái máy xây dựng', slug: 'lai-may-xay-dung' },
          { name: 'Lái máy xúc', slug: 'lai-may-xuc' },
          { name: 'Lái máy xúc lật', slug: 'lai-may-xuc-lat' },
          { name: 'Lái xe lu', slug: 'lai-xe-lu' },
          { name: 'Làm nền, móng', slug: 'lam-nen-mong' },
          { name: 'Lắp bồn tắm', slug: 'lap-bon-tam' },
          { name: 'Lắp đặt đường ống', slug: 'lap-dat-duong-ong' },
          { name: 'Lắp đặt lò nung-xây dựng', slug: 'lap-dat-lo-nung-xay-dung' },
          { name: 'Lắp đặt pin năng lượng', slug: 'lap-dat-pin-nang-luong' },
          { name: 'Lắp điện lạnh, điều hòa', slug: 'lap-dien-lanh-dieu-hoa' },
          { name: 'Lắp ghép cốt thép', slug: 'lap-ghep-cot-thep' },
          { name: 'Lát đá', slug: 'lat-da' },
          { name: 'Lợp mái nhà', slug: 'lop-mai-nha' },
          { name: 'Lợp ngói', slug: 'lop-ngoi' },
          { name: 'Mộc cốp pha', slug: 'moc-cop-pha' },
          { name: 'Nội thất gỗ-xây dựng', slug: 'noi-that-go-xay-dung' },
          { name: 'Ốp lát gạch', slug: 'op-lat-gach' },
          { name: 'Phá dỡ', slug: 'pha-do' },
          { name: 'San lấp mặt bằng', slug: 'san-lap-mat-bang' },
          { name: 'Sản xuất bê tông', slug: 'san-xuat-be-tong' },
          { name: 'Sơn xây dựng', slug: 'son-xay-dung' },
          { name: 'Tấm kim loại kiến trúc', slug: 'tam-kim-loai-kien-truc' },
          { name: 'Tấm kim loại ống gió', slug: 'tam-kim-loai-ong-gio' },
          { name: 'Thi công dán tường', slug: 'thi-cong-dan-tuong' },
          { name: 'Thi công lắp rèm', slug: 'thi-cong-lap-rem' },
          { name: 'Thi công móng thép', slug: 'thi-cong-mong-thep' },
          { name: 'Thợ mộc xây dựng', slug: 'tho-moc-xay-dung' },
          { name: 'Trát vữa', slug: 'trat-vua' },
          { name: 'Xây dựng tổng hợp', slug: 'xay-dung-tong-hop' }
      ] },
      { name: 'Vệ sinh toà nhà', slug: 've-sinh-toa-nha-tokutei', keywords: [
          { name: 'Buồng phòng khách sạn', slug: 'buong-phong-khach-san' },
          { name: 'Vệ sinh toà nhà', slug: 've-sinh-toa-nha' }
      ] },
      { name: 'Lưu trú, khách sạn', slug: 'luu-tru-khach-san-tokutei', keywords: [
          { name: '(Khách sạn) Tiếp khách, quản lý vệ sinh', slug: 'khach-san-tiep-khach-quan-ly-ve-sinh' },
          { name: 'Hành lý khách sạn', slug: 'hanh-ly-khach-san' },
          { name: 'Lễ tân khách sạn', slug: 'le-tan-khach-san' },
          { name: 'Lưu trú khách sạn', slug: 'luu-tru-khach-san' },
          { name: 'Quản lý khách sạn', slug: 'quan-ly-khach-san' }
      ] },
      { name: 'Điều dưỡng', slug: 'dieu-duong-tokutei', keywords: [
          { name: 'điều dưỡng', slug: 'dieu-duong' },
          { name: 'chăm sóc người già', slug: 'cham-soc-nguoi-gia' },
          { name: 'hộ lý', slug: 'ho-ly' }
      ] }
    ],
    'ky-su-tri-thuc': [
      { name: "Nông lâm ngư nghiệp", slug: "nong-lam-ngu-nghiep-ks", keywords: [
          { name: "Chăn nuôi", slug: "chan-nuoi" },
          { name: "Công nghệ nông, lâm, ngư nghiệp", slug: "cong-nghe-nong-lam-ngu-nghiep" },
          { name: "Công nhân chăn nuôi đặc khu", slug: "cong-nhan-chan-nuoi-dac-khu" },
          { name: "Công nhân Nông, Lâm, Ngư nghiệp", slug: "cong-nhan-nong-lam-ngu-nghiep" },
          { name: "Công nhân trồng trọt đặc khu", slug: "cong-nhan-trong-trot-dac-khu" }
      ] },
      { name: "Thực phẩm", slug: "thuc-pham-ks", keywords: [
          { name: "thực phẩm", slug: "thuc-pham" },
          { name: "đồ uống", slug: "do-uong" }
      ] },
      { name: "Sản xuất, chế tạo, công nghệ", slug: "san-xuat-cong-nghe-ks", keywords: [
          { name: "Công nghệ môi trường", slug: "cong-nghe-moi-truong" },
          { name: "Công nghệ sản xuất", slug: "cong-nghe-san-xuat" },
          { name: "Công nhân sản xuất, gia công sản phẩm (trừ kim loại, máy móc)", slug: "cong-nhan-san-xuat-gia-cong-san-pham" },
          { name: "Gia công đồ xa xỉ", slug: "gia-cong-do-xa-xi" },
          { name: "Hoá học làm xưởng", slug: "hoa-hoc-lam-xuong" },
          { name: "In ấn", slug: "in-an" },
          { name: "IT làm xưởng", slug: "it-lam-xuong" },
          { name: "Khoan khảo sát dầu mỏ, năng lượng", slug: "khoan-khao-sat-dau-mo-nang-luong" },
          { name: "Kinh tế làm xưởng", slug: "kinh-te-lam-xuong" },
          { name: "Lao động nước ngoài lĩnh vực sản xuất", slug: "lao-dong-nuoc-ngoai-linh-vuc-san-xuat" },
          { name: "May mặc", slug: "may-mac" },
          { name: "Môi trường làm xưởng", slug: "moi-truong-lam-xuong" },
          { name: "Nhân viên sân bay", slug: "nhan-vien-san-bay" },
          { name: "Quản lý sản xuất tổng hợp", slug: "quan-ly-san-xuat-tong-hop" },
          { name: "Rác thải, phế liệu, tái chế", slug: "rac-thai-phe-lieu-tai-che" },
          { name: "Sản xuất sản phẩm", slug: "san-xuat-san-pham" },
          { name: "Sản xuất sản phẩm cho nước ngoài", slug: "san-xuat-san-pham-cho-nuoc-ngoai" },
          { name: "Thiết kế thời trang", slug: "thiet-ke-thoi-trang" }
      ] },
      { name: "Cơ khí, máy móc", slug: "co-khi-may-moc-ks", keywords: [
          { name: "Bảo trì hệ thống điện", slug: "bao-tri-he-thong-dien" },
          { name: "Bảo trì máy móc", slug: "bao-tri-may-moc" },
          { name: "Chế tạo máy", slug: "che-tao-may" },
          { name: "Cơ khí", slug: "co-khi" },
          { name: "Công nghệ cơ khí", slug: "cong-nghe-co-khi" },
          { name: "Công nhân đóng tàu nước ngoài", slug: "cong-nhan-dong-tau-nuoc-ngoai" },
          { name: "Công nhân sản xuất, gia công kim loại", slug: "cong-nhan-san-xuat-gia-cong-kim-loai" },
          { name: "Điện cơ khí hỗ trợ chuyển nhà", slug: "dien-co-khi-ho-tro-chuyen-nha" },
          { name: "Điện nội thất", slug: "dien-noi-that" },
          { name: "Điện, kỹ thuật điện", slug: "dien-ky-thuat-dien" },
          { name: "Gia công cơ khí", slug: "gia-cong-co-khi" },
          { name: "Kiểm tra máy móc", slug: "kiem-tra-may-moc" },
          { name: "Lắp đặt điều hoà", slug: "lap-dat-dieu-hoa" },
          { name: "Lắp đặt máy móc", slug: "lap-dat-may-moc" },
          { name: "Lắp đặt tủ lạnh", slug: "lap-dat-tu-lanh" },
          { name: "Lắp ráp máy móc", slug: "lap-rap-may-moc" },
          { name: "Phân tích CAE", slug: "phan-tich-cae" },
          { name: "Quản lý sản xuất máy", slug: "quan-ly-san-xuat-may" },
          { name: "Thiết kế Auto CAD", slug: "thiet-ke-auto-cad" },
          { name: "Thiết kế cơ khí", slug: "thiet-ke-co-khi" },
          { name: "Thiết kế điện", slug: "thiet-ke-dien" },
          { name: "Tự động hoá", slug: "tu-dong-hoa" },
          { name: "Vận hành máy", slug: "van-hanh-may" },
          { name: "Vận hành máy CNC", slug: "van-hanh-may-cnc" },
          { name: "Vận hành máy ép", slug: "van-hanh-may-ep" },
          { name: "Vận hành máy ép nhựa", slug: "van-hanh-may-ep-nhua" },
          { name: "Vận hành robot", slug: "van-hanh-robot" },
          { name: "Viễn thông", slug: "vien-thong" }
      ] },
      { name: "Công nghệ ô tô", slug: "cong-nghe-o-to-ks", keywords: [
          { name: "ô tô", slug: "o-to" },
          { name: "thiết kế ô tô", slug: "thiet-ke-o-to" }
      ] },
      { name: "Vận chuyển hàng hóa", slug: "van-chuyen-hang-hoa-ks", keywords: [
          { name: "Đại lý thủ tục hàng hải", slug: "dai-ly-thu-tuc-hang-hai" },
          { name: "Quản lý dọn dẹp", slug: "quan-ly-don-dep" },
          { name: "Quản lý đóng gói", slug: "quan-ly-dong-goi" },
          { name: "Quản lý vận chuyển", slug: "quan-ly-van-chuyen" },
          { name: "Quản lý vận chuyển, dọn dẹp, đóng gói", slug: "quan-ly-van-chuyen-don-dep-dong-goi" }
      ] },
      { name: "Xây dựng", slug: "xay-dung-ks", keywords: [
          { name: "Cầu đường", slug: "cau-duong" },
          { name: "Công nghệ xây dựng của nước ngoài", slug: "cong-nghe-xay-dung-cua-nuoc-ngoai" },
          { name: "Công nhân kết cấu xây dựng", slug: "cong-nhan-ket-cau-xay-dung" },
          { name: "Công nhân xây dựng (trừ khung công trình)", slug: "cong-nhan-xay-dung" },
          { name: "Công nhân xây dựng mỏ tổng hợp", slug: "cong-nhan-xay-dung-mo-tong-hop" },
          { name: "Công nhân xây dựng nước ngoài", slug: "cong-nhan-xay-dung-nuoc-ngoai" },
          { name: "Đường ống", slug: "duong-ong" },
          { name: "Giám sát thi công", slug: "giam-sat-thi-cong" },
          { name: "Hoàn thiện nội thất", slug: "hoan-thien-noi-that" },
          { name: "Khảo sát", slug: "khao-sat" },
          { name: "Kiến trúc sư", slug: "kien-truc-su" },
          { name: "Kỹ thuật Khảo sát", slug: "ky-thuat-khao-sat" },
          { name: "Kỹ thuật Kiến trúc", slug: "ky-thuat-kien-truc" },
          { name: "Kỹ thuật Kiến trúc, Xây dựng, Khảo sát", slug: "ky-thuat-kien-truc-xay-dung-khao-sat" },
          { name: "Kỹ thuật Xây dựng", slug: "ky-thuat-xay-dung" },
          { name: "Nội thất gỗ", slug: "noi-that-go" },
          { name: "Quản lý, giám sát thi công công trình", slug: "quan-ly-giam-sat-thi-cong-cong-trinh" },
          { name: "Trắc địa, khảo sát", slug: "trac-dia-khao-sat" },
          { name: "Xây dựng dân dụng", slug: "xay-dung-dan-dung" }
      ] },
      { name: "Khách sạn, lưu trú", slug: "khach-san-luu-tru-ks", keywords: [
          { name: "Dịch vụ khách sạn", slug: "dich-vu-khach-san" },
          { name: "Khu nghỉ dưỡng", slug: "khu-nghi-duong" },
          { name: "Lễ tân khách sạn", slug: "le-tan-khach-san" }
      ] },
      { name: "Y tế, điều dưỡng", slug: "y-te-dieu-duong-ks", keywords: [
          { name: "Bác sĩ", slug: "bac-si" },
          { name: "Bác sĩ chỉnh thị lực", slug: "bac-si-chinh-thi-luc" },
          { name: "Chuyên viên phục hình", slug: "chuyen-vien-phuc-hinh" },
          { name: "Điều dưỡng có chứng chỉ", slug: "dieu-duong-co-chung-chi" },
          { name: "Điều dưỡng dự bị học EPA", slug: "dieu-duong-du-bi-hoc-epa" },
          { name: "Điều dưỡng, hộ lý EPA", slug: "dieu-duong-ho-ly-epa" },
          { name: "Điều dưỡng, hộ lý EPA dự bị", slug: "dieu-duong-ho-ly-epa-du-bi" },
          { name: "Dược sĩ", slug: "duoc-si" },
          { name: "Kỹ thuật viên X quang", slug: "ky-thuat-vien-x-quang" },
          { name: "Nha sĩ", slug: "nha-si" },
          { name: "Nhà trị liệu nghề nghiệp", slug: "nha-tri-lieu-nghe-nghiep" },
          { name: "Nữ hộ sinh", slug: "nu-ho-sinh" },
          { name: "Trợ lý y tá", slug: "tro-ly-y-ta" },
          { name: "Vật lý trị liệu", slug: "vat-ly-tri-lieu" },
          { name: "Vệ sinh răng miệng", slug: "ve-sinh-rang-mieng" },
          { name: "Y tá", slug: "y-ta" },
          { name: "Y tá EPA", slug: "y-ta-epa" },
          { name: "Y tá EPA dự bị", slug: "y-ta-epa-du-bi" },
          { name: "Y tá sức khoẻ cộng đồng", slug: "y-ta-suc-khoe-cong-dong" },
          { name: "Y tế lâm sàng", slug: "y-te-lam-sang" }
      ] },
      { name: "Kinh doanh, kinh tế", slug: "kinh-doanh-kinh-te-ks", keywords: [
          { name: "Bán hàng miễn thuế", slug: "ban-hang-mien-thue" },
          { name: "Dịch vụ bán hàng", slug: "dich-vu-ban-hang" },
          { name: "Dịch vụ khách hàng tổng hợp", slug: "dich-vu-khach-hang-tong-hop" },
          { name: "Điều hành", slug: "dieu-hanh" },
          { name: "Hoạt động khởi nghiệp", slug: "hoat-dong-khoi-nghiep" },
          { name: "Kinh doanh kế toán", slug: "kinh-doanh-ke-toan" },
          { name: "Kinh tế", slug: "kinh-te" },
          { name: "Nghiên cứu thị trường, marketing", slug: "nghien-cuu-thi-truong-marketing" },
          { name: "Nhân viên dịch vụ khác (không phân loại nơi khác)", slug: "nhan-vien-dich-vu-khac" },
          { name: "Quản lý", slug: "quan-ly" },
          { name: "Quản lý kế hoạch quảng cáo, truyền thông", slug: "quan-ly-ke-hoach-quang-cao-truyen-thong" },
          { name: "Thương mại nước ngoài", slug: "thuong-mai-nuoc-ngoai" },
          { name: "Tiếp thị (sales) doanh nghiệp", slug: "tiep-thi-sales-doanh-nghiep" }
      ] },
      { name: "Tài chính, kế toán, bảo hiểm", slug: "tai-chinh-ke-toan-ks", keywords: [
          { name: "Kế toán công chứng", slug: "ke-toan-cong-chung" },
          { name: "Kế toán công chứng nước ngoài", slug: "ke-toan-cong-chung-nuoc-ngoai" },
          { name: "Kế toán thuế", slug: "ke-toan-thue" },
          { name: "Tài chính, bảo hiểm", slug: "tai-chinh-bao-hiem" },
          { name: "Tư vấn bảo hiểm xã hội", slug: "tu-van-bao-hiem-xa-hoi" }
      ] },
      { name: "Báo chí, truyền thông, marketing", slug: "bao-chi-marketing-ks", keywords: [
          { name: "Báo chí", slug: "bao-chi" },
          { name: "Biên tập", slug: "bien-tap" },
          { name: "Digital Marketing", slug: "digital-marketing" },
          { name: "Marketing", slug: "marketing" },
          { name: "Nhà báo", slug: "nha-bao" },
          { name: "Thiết kế Marketing", slug: "thiet-ke-marketing" },
          { name: "Truyền thông", slug: "truyen-thong" },
          { name: "Viết quảng cáo", slug: "viet-quang-cao" }
      ] },
      { name: "Công nghệ thông tin", slug: "it-ks", keywords: [
          { name: "Công nghệ thông tin", slug: "cong-nghe-thong-tin" },
          { name: "IT", slug: "it" },
          { name: "lập trình", slug: "lap-trinh" },
          { name: "phần mềm", slug: "phan-mem" },
          { name: "Blockchain", slug: "blockchain" },
          { name: "BrSE (Bridge System Engineer)", slug: "brse" },
          { name: "Business Analyst (BA)", slug: "business-analyst" },
          { name: "COO (Chief Operation Officer)", slug: "coo" },
          { name: "CTO (Chief Technology Officer)", slug: "cto" },
          { name: "ITM (Information Technical Manager)", slug: "itm" },
          { name: "Lập trình nhúng", slug: "lap-trinh-nhung" },
          { name: "Lập trình viên", slug: "lap-trinh-vien" },
          { name: "PM (Product Manager)", slug: "product-manager" },
          { name: "PO (Product Owner)", slug: "product-owner" },
          { name: "Tester", slug: "tester" },
          { name: "Thiết kế UI, UX", slug: "thiet-ke-ui-ux" },
          { name: "Trí tuệ nhân tạo", slug: "tri-tue-nhan-tao" },
          { name: "Vận hành web thương mại điện tử", slug: "van-hanh-web-thuong-mai-dien-tu" }
      ] },
      { name: "Nghiên cứu, phân tích", slug: "nghien-cuu-phan-tich-ks", keywords: [
          { name: "Khảo sát đất đai, nhà ở", slug: "khao-sat-dat-dai-nha-o" },
          { name: "Nghiên cứu", slug: "nghien-cuu" },
          { name: "Nghiên cứu thị trường", slug: "nghien-cuu-thi-truong" }
      ] },
      { name: "Giáo dục, đào tạo", slug: "giao-duc-dao-tao-ks", keywords: [
          { name: "Giảng dạy có chứng chỉ", slug: "giang-day-co-chung-chi" },
          { name: "Giảng dạy đại học", slug: "giang-day-dai-hoc" },
          { name: "Giảng dạy ngoài cơ sở giáo dục", slug: "giang-day-ngoai-co-so-giao-duc" },
          { name: "Giảng dạy ngôn ngữ tại Tiểu học, THCS, PTTH", slug: "giang-day-ngon-ngu-tai-tieu-hoc-thcs-ptth" },
          { name: "Giảng dạy trường dạy nghề (Senmon)", slug: "giang-day-truong-day-nghe-senmon" },
          { name: "Giảng dạy trường học các loại", slug: "giang-day-truong-hoc-cac-loai" },
          { name: "Giảng dạy trường quốc tế", slug: "giang-day-truong-quoc-te" },
          { name: "Hướng dẫn nghiên cứu", slug: "huong-dan-nghien-cuu" },
          { name: "Hướng dẫn thể thao", slug: "huong-dan-the-thao" }
      ] },
      { name: "Hành chính, văn phòng", slug: "hanh-chinh-van-phong-ks", keywords: [
          { name: "Biên dịch, phiên dịch", slug: "bien-dich-phien-dich" },
          { name: "Nhân viên văn phòng", slug: "nhan-vien-van-phong" }
      ] },
      { name: "Pháp lý", slug: "phap-ly-ks", keywords: [
          { name: "pháp lý", slug: "phap-ly" },
          { name: "luật sư", slug: "luat-su" }
      ] },
      { name: "Nghệ thuật, nghệ sĩ", slug: "nghe-thuat-ks", keywords: [
          { name: "Mỹ thuật gia", slug: "my-thuat-gia" },
          { name: "nhiếp ảnh gia", slug: "nhiep-anh-gia" },
          { name: "Nhà văn", slug: "nha-van" },
          { name: "Nhạc sĩ", slug: "nhac-si" },
          { name: "nghệ sĩ sân khấu", slug: "nghe-si-san-khau" }
      ] },
      { name: "Thể dục thể thao", slug: "the-thao-ks", keywords: [
          { name: "Vận động viên chuyên nghiệp", slug: "van-dong-vien-chuyen-nghiep" },
          { name: "Vận động viên nghiệp dư", slug: "van-dong-vien-nghiep-du" }
      ] },
      { name: "Nghề có kỹ năng chuyên nghiệp", slug: "nghe-chuyen-nghiep-ks", keywords: [
          { name: "Công chức", slug: "cong-chuc" },
          { name: "Giúp việc gia đình đặc khu", slug: "giup-viec-gia-dinh-dac-khu" },
          { name: "Huấn luyện động vật", slug: "huan-luyen-dong-vat" },
          { name: "Nấu nướng", slug: "nau-nuong" },
          { name: "Người pha chế rượu", slug: "nguoi-pha-che-ruou" },
          { name: "Người quản gia", slug: "nguoi-quan-gia" },
          { name: "Nhà ngoại giao", slug: "nha-ngoai-giao" },
          { name: "Nhân viên tôn giáo", slug: "nhan-vien-ton-giao" },
          { name: "Phi công", slug: "phi-cong" }
      ] },
      { name: "Việc làm bán chuyên nghiệp", slug: "viec-lam-ban-chuyen-nghiep-ks", keywords: [
          { name: "Công việc mùa hè", slug: "cong-viec-mua-he" },
          { name: "Lao động kỳ nghỉ", slug: "lao-dong-ky-nghi" },
          { name: "Sinh viên thực tập", slug: "sinh-vien-thuc-tap" },
          { name: "Trao đổi văn hóa quốc tế", slug: "trao-doi-van-hoa-quoc-te" }
      ] }
    ]
};

export const industryGroups = {
  'Công xưởng': ['Chế biến thực phẩm', 'Cơ khí', 'Điện tử', 'Dệt may', 'May mặc', 'Cơ khí, kim loại', 'Cơ khí, chế tạo máy', 'Điện, điện tử'],
  'Ngoài trời': ['Xây dựng', 'Nông nghiệp', 'Ngư nghiệp'],
  'Dịch vụ & Chăm sóc con người': ['Điều dưỡng', 'Nhà hàng', 'Vận tải', 'Lưu trú, khách sạn', 'Vệ sinh toà nhà', 'Hàng không'],
};
