
export type Industry = {
    name: string;
    slug: string;
    keywords: string[];
};

const defaultIndustries: Industry[] = [
    { name: 'Công nghệ thông tin', slug: 'it', keywords: ['it', 'công nghệ thông tin', 'software', 'phần mềm', 'developer', 'lập trình'] },
    { name: 'Cơ khí', slug: 'co-khi', keywords: ['cơ khí', 'chế tạo máy', 'tiện', 'phay', 'bào', 'hàn', 'hàn xì', 'CNC', 'vận hành máy', 'bảo trì', 'sửa chữa', 'đứng máy', 'luyện kim'] },
    { name: 'Dệt may', slug: 'det-may', keywords: ['dệt may', 'may mặc', 'thời trang', 'sợi', 'nhuộm', 'hoàn tất vải'] },
    { name: 'Điện tử', slug: 'dien-tu', keywords: ['điện tử', 'lắp ráp', 'linh kiện', 'kiểm tra', 'QC', 'QA', 'sản xuất'] },
    { name: 'Logistics', slug: 'logistics', keywords: ['logistics', 'vận tải', 'kho bãi', 'xuất nhập khẩu', 'supply chain', 'chuỗi cung ứng'] }
];

export const industriesByJobType: { [key: string]: Industry[] } = {
    'Thực tập sinh kỹ năng': [
      { name: 'Ngư nghiệp', slug: 'ngu-nghiep-tts', keywords: ["Câu cá ngừ cần và dây", "Câu mực", "Câu tôm, cua bằng lồng", "Đánh cá dây câu dài", "Đánh cá lưới kéo", "Đánh cá lưới rê", "Đánh cá lưới sào", "Đánh cá lưới thả", "Đặt lưới đánh cá", "Nuôi sò điệp"] },
      { name: 'Nông nghiệp', slug: 'nong-nghiep-tts', keywords: ["Chăn nuôi bò", "Chăn nuôi bò sữa", "Chăn nuôi gà", "Chăn nuôi lợn", "Nhặt trứng gà", "Nông nghiệp chăn nuôi", "Nông nghiệp trồng trọt", "Thu hoạch bắp cải", "Thu hoạch cà chua", "Thu hoạch dâu tây", "Thu hoạch hoa", "Thu hoạch hoa quả", "Thu hoạch rau củ", "Trồng cây ăn quả", "Trồng nấm", "Trồng nấm công nghệ cao", "Trồng rau củ", "Trồng trọt nhà kính"] },
      { name: 'Thực phẩm', slug: 'thuc-pham-tts', keywords: ["Bánh gạo", "Bánh kẹo", "Bánh ngọt", "Bếp viện", "Chế biến cá", "Chế biến đồ ăn sẵn", "Chế biến gia cầm", "Chế biến sushi", "Chế biến thịt bò, lợn", "Chế biến thuỷ sản sống", "Chiết xuất thuỷ sản", "Cơm hộp", "Cơm nắm", "Cửa hàng siêu thị", "Đậu hũ", "Đồ ăn kèm", "Đồ konbini", "Đóng gói bánh kẹo", "Đóng gói cafe", "Đóng gói gạo", "Đóng gói rau", "Đóng gói rau củ", "Đóng gói rong biển", "Đóng gói thanh cua", "Đóng hộp thực phẩm", "Gia công đồ ăn liền", "Giăm bông, xúc xích...", "Há cảo", "Làm bánh kẹo", "Mỳ tôm", "Salad", "Sản xuất bánh mì", "Sản xuất dưa muối", "Sản xuất mắm cá", "Sản xuất mỳ", "Siêu thị", "Tẩm ướp thuỷ sản", "Thái cá sashimi", "Thịt bò", "Thịt gà", "Thịt lợn", "Thức ăn cơ sở y tế", "Thực phẩm", "Thực phẩm sữa", "Thực phẩm trứng", "Thuỷ sản gia công chế biến", "Thuỷ sản khô", "Thuỷ sản lên men", "Thuỷ sản sấy khô", "Thuỷ sản ủ muối", "Thuỷ sản xông khói"] },
      { name: 'Sản xuất, dịch vụ tổng hợp', slug: 'san-xuat-dich-vu-tong-hop-tts', keywords: ["(Khách sạn) Tiếp khách, quản lý vệ sinh", "Bảo dưỡng ô tô", "Bảo trì đường sắt", "Buồng phòng khách sạn", "Công việc cưa gỗ", "Điều dưỡng, hộ lý", "Dọn dẹp khoang hành khách", "Đóng gói", "Đóng gói công nghiệp", "Đóng gói mỹ phẩm", "Đóng sách", "Đúc gốm bằng áp lực", "Đúc khuôn cao su", "Đục lỗ hộp in", "Đúc nhựa", "Đúc nhựa cán xếp chồng", "Đục nhựa ép phun", "Đúc nhựa nén", "Đúc nhựa thổi định hình", "Đúc nhựa thổi phồng", "Gia công đồ gia dụng", "Gia công ép đùn cao su", "Gia công sản phẩm gỗ", "Gỗ ép", "Hàng hóa hàng không", "Hỗ trợ mặt đất máy bay", "In gốm", "In offset", "In ống đồng", "In vỏ bánh kẹo", "Kiểm tra linh kiện ô tô", "Kiểm tra sản phẩm nhựa", "Lắp ráp linh kiện ô tô", "Linh kiện ô tô", "Nặn gốm bằng bánh xoay", "Nhiên liệu rắn từ rác", "Sản xuất hộp bìa cứng", "Sản xuất hộp in", "Sản xuất hộp nhãn dán", "Sản xuất linh kiện", "Sản xuất pin năng lượng", "Sản xuất vải lanh", "Sửa chữa ô tô", "Thiết bị khí nén đường sắt", "Trộn và cán cao su", "Vật liệu composite nhiều lớp", "Vệ sinh phòng học", "Vệ sinh toà nhà", "Vệ sinh văn phòng"] },
      { name: 'Cơ khí, kim loại', slug: 'co-khi-kim-loai-tts', keywords: ["Bản mạch in", "Bảo trì máy móc", "Chế tạo kim loại tấm", "Chế tạo máy", "Cơ khí", "Cuộn dây máy điện quay", "Dập khuôn kim loại", "Điện", "Điện tử", "Đóng tàu", "Đúc", "Đúc gang", "Đúc khuôn", "Đúc khuôn buồng lạnh", "Đúc khuôn buồng nóng", "Đúc kim loại màu", "Ép dập kim loại", "Gia công cơ khí", "Gia công ép đùn", "Gia công kim loại - Tekko", "Gia công tinh", "Hàn", "Hàn bán tự động", "Hàn kết cấu", "Hàn khí", "Hàn khung thép", "Hàn tàu", "Hàn thủ công", "Hàn tủ điện", "Hàn xì", "Hoàn thiện dụng cụ nung chảy", "Hoàn thiện khuôn", "Hoàn thiện sản phẩm ép đùn", "Kiểm tra máy móc", "Lắp đặt điều hoà", "Lắp đặt máy móc", "Lắp đặt tủ lạnh", "Lắp ráp điện", "Lắp ráp điện tử", "Lắp ráp linh kiện bán dẫn", "Lắp ráp máy biến áp", "Lắp ráp thiết bị điện khí", "Lắp ráp thiết bị điện quay", "Lắp ráp thiết bị điện tử", "Lắp thiết bị đóng, mở", "Lắp tủ điện, tủ điều khiển", "Mạ điện", "Mạ kẽm nhúng nóng", "Máy sản xuất tấm kim loại", "Rèn", "Rèn bằng búa", "Sơn", "Sơn cầu thép", "Sơn công trình xây dựng", "Sơn kim loại", "Sơn phun", "Sử dụng máy phay", "Sử dụng máy tiện số", "Sử dụng máy tiện thường", "Thi công điện", "Thi công kết cấu thép", "Thiết kế bảng mạch in", "Vận hành máy", "Vận hành máy CNC", "Vận hành máy ép", "Vận hành máy ép nhựa", "Vận hành robot", "Xử lý điện hóa nhôm"] },
      { name: 'Xây dựng', slug: 'xay-dung-tts', keywords: ["Bê tông", "Buộc thép", "Chống thấm", "Cốp pha công trình", "Dán tường", "Đổ bê tông áp lực", "Đổ nhựa đường", "Dựng giàn giáo", "Đường ống", "Đường ống điều hoà", "Đường ống nhà máy", "Đường ống nước", "Đường ống xây dựng", "Gia công đường ống", "Gia công khung thép", "Gia công khung thép trong xưởng", "Gia công sắt trong xưởng", "Gia công vật liệu đá", "Hàn khung thép trên cao", "Hoàn thiện nội thất", "Hoàn thiện sàn nhựa", "Hoàn thiện sàn thảm", "Hoàn thiện ván", "Hút nước ngầm công trình", "Khoan giếng máy dập", "Khoan giếng máy khoan", "Khung chắn toà nhà", "Lái máy ủi", "Lái máy xây dựng", "Lái máy xúc", "Lái máy xúc lật", "Lái xe lu", "Làm nền, móng", "Lắp bồn tắm", "Lắp đặt đường ống", "Lắp đặt lò nung-xây dựng", "Lắp đặt pin năng lượng", "Lắp điện lạnh, điều hòa", "Lắp ghép cốt thép", "Lát đá", "Lợp mái nhà", "Lợp ngói", "Mộc cốp pha", "Nội thất gỗ-xây dựng", "Ốp lát gạch", "Phá dỡ", "San lấp mặt bằng", "Sản xuất bê tông", "Sơn xây dựng", "Tấm kim loại kiến trúc", "Tấm kim loại ống gió", "Thi công dán tường", "Thi công lắp rèm", "Thi công móng thép", "Thợ mộc xây dựng", "Trát vữa", "Xây dựng tổng hợp"] },
      { name: 'May mặc', slug: 'may-mac-tts', keywords: ["Chăn ga gối đệm", "Công việc trước kéo sợi", "Công việc trước khi dệt", "Dệt hoàn thiện", "Dệt kim máy sợi dọc", "Dệt may", "Gia công dệt", "Gia công sợi hỗn hợp", "Kéo sợi tinh", "May khăn mặt", "May mặc", "May quần áo", "May quần áo nam", "Nhuộm chỉ", "Nhuộm vải, đan len", "Quần áo phụ nữ, trẻ em", "Quấn sợi", "Sản xuất áo sơ mi", "Sản xuất đồ lót", "Sản xuất ghế ngồi ô tô", "Sản xuất máy dệt kim tròn", "Sản xuất tất", "Sản xuất thảm dệt", "Sản xuất thảm đục lỗ", "Sản xuất thảm nhung nổi", "Sản xuất vải bạt"] }
    ],
    'Kỹ năng đặc định': [
      { name: 'Ngư nghiệp', slug: 'ngu-nghiep-tokutei', keywords: ["Nuôi trồng thủy sản", "Đánh bắt cá"] },
      { name: 'Nông nghiệp', slug: 'nong-nghiep-tokutei', keywords: ["Chăn nuôi bò", "Chăn nuôi bò sữa", "Chăn nuôi gà", "Chăn nuôi lợn", "Nhặt trứng gà", "Nông nghiệp chăn nuôi", "Nông nghiệp trồng trọt", "Thu hoạch bắp cải", "Thu hoạch cà chua", "Thu hoạch dâu tây", "Thu hoạch hoa", "Thu hoạch hoa quả", "Thu hoạch rau củ", "Trồng cây ăn quả", "Trồng nấm", "Trồng nấm công nghệ cao", "Trồng rau củ", "Trồng trọt nhà kính"] },
      { name: 'Nhà hàng', slug: 'nha-hang-tokutei', keywords: ["Chạy bàn", "Mua hàng", "Nấu bếp", "Nhà hàng", "Phụ bếp", "Quản lý", "Rửa bát", "Thu ngân"] },
      { name: 'Thực phẩm', slug: 'thuc-pham-tokutei', keywords: ["Bánh gạo", "Bánh kẹo", "Bánh ngọt", "Bếp viện", "Chế biến cá", "Chế biến đồ ăn sẵn", "Chế biến gia cầm", "Chế biến sushi", "Chế biến thịt bò, lợn", "Chế biến thuỷ sản sống", "Chiết xuất thuỷ sản", "Cơm hộp", "Cơm nắm", "Cửa hàng siêu thị", "Đậu hũ", "Đồ ăn kèm", "Đồ konbini", "Đóng gói bánh kẹo", "Đóng gói cafe", "Đóng gói gạo", "Đóng gói rau", "Đóng gói rau củ", "Đóng gói rong biển", "Đóng gói thanh cua", "Đóng hộp thực phẩm", "Gia công đồ ăn liền", "Giăm bông, xúc xích...", "Há cảo", "Làm bánh kẹo", "Mỳ tôm", "Salad", "Sản xuất bánh mì", "Sản xuất dưa muối", "Sản xuất mắm cá", "Sản xuất mỳ", "Siêu thị", "Tẩm ướp thuỷ sản", "Thái cá sashimi", "Thịt bò", "Thịt gà", "Thịt lợn", "Thức ăn cơ sở y tế", "Thực phẩm", "Thực phẩm sữa", "Thực phẩm trứng", "Thuỷ sản gia công chế biến", "Thuỷ sản khô", "Thuỷ sản lên men", "Thuỷ sản sấy khô", "Thuỷ sản ủ muối", "Thuỷ sản xông khói"] },
      { name: 'Sản xuất, dịch vụ tổng hợp', slug: 'san-xuat-dich-vu-tong-hop-tokutei', keywords: ["Bảo dưỡng ô tô", "Công việc cưa gỗ", "Đóng gói", "Đóng gói công nghiệp", "Đóng gói mỹ phẩm", "Đóng sách", "Đúc gốm bằng áp lực", "Đúc khuôn cao su", "Đục lỗ hộp in", "Đúc nhựa", "Đúc nhựa cán xếp chồng", "Đục nhựa ép phun", "Đúc nhựa nén", "Đúc nhựa thổi định hình", "Đúc nhựa thổi phồng", "Gia công đồ gia dụng", "Gia công ép đùn cao su", "Gia công sản phẩm gỗ", "Gỗ ép", "In gốm", "In offset", "In ống đồng", "In vỏ bánh kẹo", "Kiểm tra sản phẩm nhựa", "Nặn gốm bằng bánh xoay", "Nhiên liệu rắn từ rác", "Sản xuất hộp bìa cứng", "Sản xuất hộp in", "Sản xuất hộp nhãn dán", "Sản xuất linh kiện", "Sản xuất pin năng lượng", "Sản xuất vải lanh", "Sửa chữa ô tô", "Thiết bị khí nén đường sắt", "Trộn và cán cao su", "Vật liệu composite nhiều lớp"] },
      { name: 'Điện, điện tử', slug: 'dien-dien-tu-tokutei', keywords: ["Bản mạch in", "Cuộn dây máy điện quay", "Điện", "Điện tử", "Lắp ráp điện", "Lắp ráp điện tử", "Lắp ráp linh kiện bán dẫn", "Lắp ráp máy biến áp", "Lắp ráp thiết bị điện khí", "Lắp ráp thiết bị điện quay", "Lắp ráp thiết bị điện tử", "Lắp thiết bị đóng, mở", "Lắp tủ điện, tủ điều khiển", "Sản xuất bảng mạch in", "Sửa chữa dụng cụ", "Sửa chữa tủ điện", "Thi công điện", "Thiết kế bảng mạch in"] },
      { name: 'Chế tạo Vật liệu', slug: 'che-tao-vat-lieu-tokutei', keywords: ["Xử lý nhiệt bề mặt", "Xử lý nhiệt một phần", "Xử lý nhiệt tổng thể"] },
      { name: 'Cơ khí, chế tạo máy', slug: 'co-khi-che-tao-may-tokutei', keywords: ["Bảo trì máy móc", "Chế tạo kim loại tấm", "Chế tạo máy", "Cơ khí", "Dập khuôn kim loại", "Đóng tàu", "Đúc", "Đúc gang", "Đúc khuôn", "Đúc khuôn buồng lạnh", "Đúc khuôn buồng nóng", "Đúc kim loại màu", "Ép dập kim loại", "Gia công cơ khí", "Gia công ép đùn", "Gia công kim loại - Tekko", "Gia công tinh", "Hàn", "Hàn bán tự động", "Hàn kết cấu", "Hàn khí", "Hàn khung thép", "Hàn tàu", "Hàn thủ công", "Hàn tủ điện", "Hàn xì", "Hoàn thiện dụng cụ nung chảy", "Hoàn thiện khuôn", "Hoàn thiện sản phẩm ép đùn", "Kiểm tra máy móc", "Lắp đặt điều hoà", "Lắp đặt máy móc", "Lắp đặt tủ lạnh", "Lắp ráp máy móc", "Máy sản xuất tấm kim loại", "Rèn", "Rèn bằng búa", "Sơn", "Sơn cầu thép", "Sơn công trình xây dựng", "Sơn kim loại", "Sơn phun", "Sử dụng máy phay", "Sử dụng máy tiện số", "Sử dụng máy tiện thường", "Thi công kết cấu thép", "Vận hành máy", "Vận hành máy CNC", "Vận hành máy ép", "Vận hành máy ép nhựa", "Vận hành robot", "Xử lý điện hóa nhôm"] },
      { name: 'Ô tô', slug: 'o-to-tokutei', keywords: ["Bảo dưỡng ô tô", "Kiểm tra linh kiện ô tô", "Lắp ráp linh kiện ô tô", "Linh kiện ô tô", "Sửa chữa ô tô"] },
      { name: 'Hàng không', slug: 'hang-khong-tokutei', keywords: ['hàng không', 'sân bay', 'bốc dỡ'] },
      { name: 'Vận tải', slug: 'van-tai-tokutei', keywords: ["Hậu cần vận tải", "Lái xe", "Lái xe buýt", "Lái xe tải", "Phụ xe", "Quản lý kho vận tải", "Thực tập lái xe"] },
      { name: 'Xây dựng', slug: 'xay-dung-tokutei', keywords: ["Bê tông", "Buộc thép", "Chống thấm", "Cốp pha công trình", "Dán tường", "Đổ bê tông áp lực", "Đổ nhựa đường", "Dựng giàn giáo", "Đường ống", "Đường ống điều hoà", "Đường ống nhà máy", "Đường ống nước", "Đường ống xây dựng", "Gia công đường ống", "Gia công khung thép", "Gia công khung thép trong xưởng", "Gia công sắt trong xưởng", "Gia công vật liệu đá", "Hàn khung thép trên cao", "Hoàn thiện nội thất", "Hoàn thiện sàn nhựa", "Hoàn thiện sàn thảm", "Hoàn thiện ván", "Hút nước ngầm công trình", "Khoan giếng máy dập", "Khoan giếng máy khoan", "Khung chắn toà nhà", "Lái máy ủi", "Lái máy xây dựng", "Lái máy xúc", "Lái máy xúc lật", "Lái xe lu", "Làm nền, móng", "Lắp bồn tắm", "Lắp đặt đường ống", "Lắp đặt lò nung-xây dựng", "Lắp đặt pin năng lượng", "Lắp điện lạnh, điều hòa", "Lắp ghép cốt thép", "Lát đá", "Lợp mái nhà", "Lợp ngói", "Mộc cốp pha", "Nội thất gỗ-xây dựng", "Ốp lát gạch", "Phá dỡ", "San lấp mặt bằng", "Sản xuất bê tông", "Sơn xây dựng", "Tấm kim loại kiến trúc", "Tấm kim loại ống gió", "Thi công dán tường", "Thi công lắp rèm", "Thi công móng thép", "Thợ mộc xây dựng", "Trát vữa", "Xây dựng tổng hợp"] },
      { name: 'Vệ sinh toà nhà', slug: 've-sinh-toa-nha-tokutei', keywords: ["Buồng phòng khách sạn", "Vệ sinh toà nhà"] },
      { name: 'Lưu trú, khách sạn', slug: 'luu-tru-khach-san-tokutei', keywords: ["(Khách sạn) Tiếp khách, quản lý vệ sinh", "Hành lý khách sạn", "Lễ tân khách sạn", "Lưu trú khách sạn", "Quản lý khách sạn"] },
      { name: 'Điều dưỡng', slug: 'dieu-duong-tokutei', keywords: ['điều dưỡng', 'chăm sóc người già', 'hộ lý'] }
    ],
    'Kỹ sư, tri thức': [
      { name: "Nông lâm ngư nghiệp", slug: "nong-lam-ngu-nghiep-ks", keywords: ["Chăn nuôi", "Công nghệ nông, lâm, ngư nghiệp", "Công nhân chăn nuôi đặc khu", "Công nhân Nông, Lâm, Ngư nghiệp", "Công nhân trồng trọt đặc khu"] },
      { name: "Thực phẩm", slug: "thuc-pham-ks", keywords: ["thực phẩm", "đồ uống"] },
      { name: "Sản xuất, chế tạo, công nghệ", slug: "san-xuat-cong-nghe-ks", keywords: ["Công nghệ môi trường", "Công nghệ sản xuất", "Công nhân sản xuất, gia công sản phẩm (trừ kim loại, máy móc)", "Gia công đồ xa xỉ", "Hoá học làm xưởng", "In ấn", "IT làm xưởng", "Khoan khảo sát dầu mỏ, năng lượng", "Kinh tế làm xưởng", "Lao động nước ngoài lĩnh vực sản xuất", "May mặc", "Môi trường làm xưởng", "Nhân viên sân bay", "Quản lý sản xuất tổng hợp", "Rác thải, phế liệu, tái chế", "Sản xuất sản phẩm", "Sản xuất sản phẩm cho nước ngoài", "Thiết kế thời trang"] },
      { name: "Cơ khí, máy móc", slug: "co-khi-may-moc-ks", keywords: ["Bảo trì hệ thống điện", "Bảo trì máy móc", "Chế tạo máy", "Cơ khí", "Công nghệ cơ khí", "Công nhân đóng tàu nước ngoài", "Công nhân sản xuất, gia công kim loại", "Điện cơ khí hỗ trợ chuyển nhà", "Điện nội thất", "Điện, kỹ thuật điện", "Gia công cơ khí", "Kiểm tra máy móc", "Lắp đặt điều hoà", "Lắp đặt máy móc", "Lắp đặt tủ lạnh", "Lắp ráp máy móc", "Phân tích CAE", "Quản lý sản xuất máy", "Thiết kế Auto CAD", "Thiết kế cơ khí", "Thiết kế điện", "Tự động hoá", "Vận hành máy", "Vận hành máy CNC", "Vận hành máy ép", "Vận hành máy ép nhựa", "Vận hành robot", "Viễn thông"] },
      { name: "Công nghệ ô tô", slug: "cong-nghe-o-to-ks", keywords: ["ô tô", "thiết kế ô tô"] },
      { name: "Vận chuyển hàng hóa", slug: "van-chuyen-hang-hoa-ks", keywords: ["Đại lý thủ tục hàng hải", "Quản lý dọn dẹp", "Quản lý đóng gói", "Quản lý vận chuyển", "Quản lý vận chuyển, dọn dẹp, đóng gói"] },
      { name: "Xây dựng", slug: "xay-dung-ks", keywords: ["Cầu đường", "Công nghệ xây dựng của nước ngoài", "Công nhân kết cấu xây dựng", "Công nhân xây dựng (trừ khung công trình)", "Công nhân xây dựng mỏ tổng hợp", "Công nhân xây dựng nước ngoài", "Đường ống", "Giám sát thi công", "Hoàn thiện nội thất", "Khảo sát", "Kiến trúc sư", "Kỹ thuật Khảo sát", "Kỹ thuật Kiến trúc", "Kỹ thuật Kiến trúc, Xây dựng, Khảo sát", "Kỹ thuật Xây dựng", "Nội thất gỗ", "Quản lý, giám sát thi công công trình", "Trắc địa, khảo sát", "Xây dựng dân dụng"] },
      { name: "Khách sạn, lưu trú", slug: "khach-san-luu-tru-ks", keywords: ["Dịch vụ khách sạn", "Khu nghỉ dưỡng", "Lễ tân khách sạn"] },
      { name: "Y tế, điều dưỡng", slug: "y-te-dieu-duong-ks", keywords: ["Bác sĩ", "Bác sĩ chỉnh thị lực", "Chuyên viên phục hình", "Điều dưỡng có chứng chỉ", "Điều dưỡng dự bị học EPA", "Điều dưỡng, hộ lý EPA", "Điều dưỡng, hộ lý EPA dự bị", "Dược sĩ", "Kỹ thuật viên X quang", "Nha sĩ", "Nhà trị liệu nghề nghiệp", "Nữ hộ sinh", "Trợ lý y tá", "Vật lý trị liệu", "Vệ sinh răng miệng", "Y tá", "Y tá EPA", "Y tá EPA dự bị", "Y tá sức khoẻ cộng đồng", "Y tế lâm sàng"] },
      { name: "Kinh doanh, kinh tế", slug: "kinh-doanh-kinh-te-ks", keywords: ["Bán hàng miễn thuế", "Dịch vụ bán hàng", "Dịch vụ khách hàng tổng hợp", "Điều hành", "Hoạt động khởi nghiệp", "Kinh doanh kế toán", "Kinh tế", "Nghiên cứu thị trường, marketing", "Nhân viên dịch vụ khác (không phân loại nơi khác)", "Quản lý", "Quản lý kế hoạch quảng cáo, truyền thông", "Thương mại nước ngoài", "Tiếp thị (sales) doanh nghiệp"] },
      { name: "Tài chính, kế toán, bảo hiểm", slug: "tai-chinh-ke-toan-ks", keywords: ["Kế toán công chứng", "Kế toán công chứng nước ngoài", "Kế toán thuế", "Tài chính, bảo hiểm", "Tư vấn bảo hiểm xã hội"] },
      { name: "Báo chí, truyền thông, marketing", slug: "bao-chi-marketing-ks", keywords: ["Báo chí", "Biên tập", "Digital Marketing", "Marketing", "Nhà báo", "Thiết kế Marketing", "Truyền thông", "Viết quảng cáo"] },
      { name: "Công nghệ thông tin", slug: "it-ks", keywords: ["Công nghệ thông tin", "IT", "lập trình", "phần mềm", "Blockchain", "BrSE (Bridge System Engineer)", "Business Analyst (BA)", "COO (Chief Operation Officer)", "CTO (Chief Technology Officer)", "ITM (Information Technical Manager)", "Lập trình nhúng", "Lập trình viên", "PM (Product Manager)", "PO (Product Owner)", "Tester", "Thiết kế UI, UX", "Trí tuệ nhân tạo", "Vận hành web thương mại điện tử"] },
      { name: "Nghiên cứu, phân tích", slug: "nghien-cuu-phan-tich-ks", keywords: ["Khảo sát đất đai, nhà ở", "Nghiên cứu", "Nghiên cứu thị trường"] },
      { name: "Giáo dục, đào tạo", slug: "giao-duc-dao-tao-ks", keywords: ["Giảng dạy có chứng chỉ", "Giảng dạy đại học", "Giảng dạy ngoài cơ sở giáo dục", "Giảng dạy ngôn ngữ tại Tiểu học, THCS, PTTH", "Giảng dạy trường dạy nghề (Senmon)", "Giảng dạy trường học các loại", "Giảng dạy trường quốc tế", "Hướng dẫn nghiên cứu", "Hướng dẫn thể thao"] },
      { name: "Hành chính, văn phòng", slug: "hanh-chinh-van-phong-ks", keywords: ["Biên dịch, phiên dịch", "Nhân viên văn phòng"] },
      { name: "Pháp lý", slug: "phap-ly-ks", keywords: ["pháp lý", "luật sư"] },
      { name: "Nghệ thuật, nghệ sĩ", slug: "nghe-thuat-ks", keywords: ["Mỹ thuật gia", "nhiếp ảnh gia", "Nhà văn", "Nhạc sĩ", "nghệ sĩ sân khấu"] },
      { name: "Thể dục thể thao", slug: "the-thao-ks", keywords: ["Vận động viên chuyên nghiệp", "Vận động viên nghiệp dư"] },
      { name: "Nghề có kỹ năng chuyên nghiệp", slug: "nghe-chuyen-nghiep-ks", keywords: ["Công chức", "Giúp việc gia đình đặc khu", "Huấn luyện động vật", "Nấu nướng", "Người pha chế rượu", "Người quản gia", "Nhà ngoại giao", "Nhân viên tôn giáo", "Phi công"] },
      { name: "Việc làm bán chuyên nghiệp", slug: "viec-lam-ban-chuyen-nghiep-ks", keywords: ["Công việc mùa hè", "Lao động kỳ nghỉ", "Sinh viên thực tập", "Trao đổi văn hóa quốc tế"] }
    ],
    'Default': defaultIndustries,
};
